### ISSUE TITLE
There is no current event loop in thread bug {bug}

### ISSUE THREAD

**Issue by sulynajimsj** [davidteather/TikTok-Api#1002]
Fill Out the template :)

For some reason I keep getting this thread error when using the titkok api

I keep getting this error when I run the code I do not know why this happens with TikTokAPI

Error:

File "C:\Users\SulyS\OneDrive\Desktop\AiSearchv1\app2.py", line 17, in
titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")
File "C:\Users\SulyS\OneDrive\Desktop\AiSearchv1\app2.py", line 9, in titkok
with TikTokApi(custom_device_id=did) as api:
File "c:\users\sulys\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 159, in init
self._initialize(
File "c:\users\sulys\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 205, in _initialize
self._browser = asyncio.get_event_loop().run_until_complete(
File "c:\users\sulys\appdata\local\programs\python\python38\lib\asyncio\events.py", line 639, in get_event_loop
raise RuntimeError('There is no current event loop in thread %r.'

**import streamlit as st
from TikTokApi import TikTokApi
import random

st.write("TikTok Scrape examples")

def titkok(link):
did = str(random.randint(10000, 999999999))
with TikTokApi(custom_device_id=did) as api:
video = api.video(id=id)
video_data = video.bytes()

    with open(f"out.mp4", "wb") as out_file:
        out_file.write(video_data)
if (2==2):
titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")**

# Code Goes Here
import streamlit as st
from TikTokApi import TikTokApi
import random

st.write("TikTok Scrape examples")

def titkok(link):
    did = str(random.randint(10000, 999999999))
    with TikTokApi(custom_device_id=did) as api:
        video = api.video(id=id)
        video_data = video.bytes()

        with open(f"out.mp4", "wb") as out_file:
            out_file.write(video_data)

if (2==2):
    titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")

**Comment by alejandroarmas** [comment]
I'm getting the same problem


```
Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/alejandro/Library/Caches/pypoetry/virtualenvs/nif-bSN8lql9-py3.10/lib/python3.10/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/Users/alejandro/Library/Caches/pypoetry/virtualenvs/nif-bSN8lql9-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/alejandro/Library/Caches/pypoetry/virtualenvs/nif-bSN8lql9-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/alejandro/Programming/AISC/NIF/src/pipelines/tiktok_videos/flow.py", line 42, in video_scraper_wrapper
    video_saver()
  File "/Users/alejandro/Programming/AISC/NIF/src/data/video_scraper.py", line 113, in video_saver
    download_video_and_frames(file_name=f'{file_path_prefix}{idempotency_hash}', video_id=video_id)
  File "/Users/alejandro/Programming/AISC/NIF/src/data/video_scraper.py", line 57, in download_video_and_frames
    with TikTokApi(custom_device_id=did) as api:
  File "/Users/alejandro/Library/Caches/pypoetry/virtualenvs/nif-bSN8lql9-py3.10/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 159, in __init__
    self._initialize(
  File "/Users/alejandro/Library/Caches/pypoetry/virtualenvs/nif-bSN8lql9-py3.10/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 205, in _initialize
    self._browser = asyncio.get_event_loop().run_until_complete(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'WorkerThread'.
```

**Comment by davidteather** [comment]
V6 fully async should solve
