### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by oryondark** [davidteather/TikTok-Api#1011]
I couldn't got the video list from below example code.
```py
from TikTokApi import TikTokApi

# Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
with TikTokApi() as api:
    for trending_video in api.trending.videos(count=50):
        # Prints the author's username of the trending video.
        print(trending_video.author.username)
```

This code show error logs to me.
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/TikTokApi/api/trending.py", line 59, in videos
    res = Trending.parent.get_data(path, ttwid=ttwid, **kwargs)
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 269, in get_data
    full_url, calc_tt_params=send_tt_params, **kwargs
  File "/Users/home/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/TikTokApi/browser_utilities/browser.py", line 220, in sign_url
    }"""
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/playwright/async_api/_generated.py", line 8591, in evaluate
    expression=expression, arg=mapping.to_impl(arg)
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/playwright/_impl/_page.py", line 411, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/playwright/_impl/_frame.py", line 281, in evaluate
    arg=serialize_argument(arg),
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 62, in send
    lambda: self.inner_send(method, params, False)
  File "//Users/home/scraper/venv/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/Users/home/scraper/venv/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: undefined is not an object (evaluating 'S[A][m(a[oprand[1]],oprand[1])]')
```

**Desktop (please complete the following information):**
 - OS: [e.g. Mac-Pro 13.3]
 - TikTokApi Version [e.g. 5.2.2] - if out of date upgrade before posting an issue

Who you are run this code ?
Can you help me? anyone...

**Comment by davidteather** [comment]
Should be fixed in V6
