### ISSUE TITLE
[BUG] - Comments are no longer retrievable

### ISSUE THREAD

**Issue by vesper8** [davidteather/TikTok-Api#1018]
Using the comments example, an empty response is returned

Tried setting the json cookie which is needed for the trending videos example to run, but it didn't help with the comments.

```

Traceback (most recent call last):
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tiktok-api/listComments.py", line 8, in <module>
    for comment in video.comments():
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/TikTokApi/api/video.py", line 170, in comments
    api_response = Video.parent.get_data(
  File "/Users/redacted/.pyenv/versions/3.10.3/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 378, in get_data
    raise EmptyResponseException(0, None,
TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://www.tiktok.com/api/comment/list/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=CA&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=1592&screen_height=1560&browser_language=en-ca&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+12_2+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F16.4+Mobile%2F15E148+Safari%2F604.1&browser_online=true&timezone_name=Europe%2FSofia&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=1&language=en&aweme_id=7107272719166901550&cursor=0&app_language=en&count=30&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&device_id=redacted&_signature=redacted
```

**Comment by jamesli1997** [comment]
+1

**Comment by nekitalek** [comment]
same issue for me

**Comment by AbdelrahmanAbounida** [comment]
+1

**Comment by RenHong-HC** [comment]
+1,Does anyone know how to fix it?

**Comment by fillies** [comment]
+1

**Comment by davidteather** [comment]
Should be fixed in V6

**Comment by binaryplatitude** [comment]
Getting this age old issue again, empty response.
