### ISSUE TITLE
Not able to acquire post data using tiktok api, help me please.

### ISSUE THREAD

**Issue by meet-cipio** [davidteather/TikTok-Api#1020]
Fill Out the template :)

**Describe the bug**

I am trying to acquire post data using API but every time I get this error or sometimes give a second error described below.

**The buggy code**
def user_posts_page(self, userID, secUID, cursor=0, **kwargs) -> dict:
        (
            region,
            language,
            proxy,
            maxCount,
            device_id,
        ) = self.__process_kwargs__(kwargs)
        kwargs["custom_device_id"] = device_id

        response = []
        query = {
            "count": 30,
            "id": userID,
            "cursor": cursor,
            "type": 1,
            "secUid": secUID,
            "sourceType": 8,
            "appId": 1233,
            "region": region,
            "priority_region": region,
            "language": language
        }
        api_url = "{}api/post/item_list/?{}&{}".format(
            BASE_URL, self.__add_url_params__(), urlencode(query)
        )

        res = self.get_data(url=api_url, send_tt_params=True, **kwargs)

        if "itemList" in res.keys():
            for t in res.get("itemList", []):
                response.append(t)

        if not res.get("hasMore", False):
            logging.info("TikTok isn't sending more TikToks beyond this point.")
            return None, response
        cursor = res["cursor"]
        return cursor, response

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
# Code Goes Here
```

**Expected behavior**

I want post_output, download it and save it to s3.

**Error Trace (if any)**
**Error 1)**
Traceback (most recent call last):
  File "/home/ubuntu/ups/acquisition/api/tiktok/__init__.py", line 34, in check_response
    return f(**kv)
  File "/home/ubuntu/ups/acquisition/api/tiktok/TikTokApi/tiktok.py", line 610, in user_posts_page
    res = self.get_data(url=api_url, send_tt_params=True, **kwargs)
  File "/home/ubuntu/ups/acquisition/api/tiktok/TikTokApi/tiktok.py", line 260, in get_data
    calc_tt_params=send_tt_params, **kwargs
  File "/home/ubuntu/ups/acquisition/api/tiktok/TikTokApi/browser_utilities/browser.py", line 192, in sign_url
    wait_until="load",
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/sync_api/_generated.py", line 7301, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/_impl/_page.py", line 484, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
**playwright._impl._api_types.Error: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www.tiktok.com/@redbull", waiting until "load"
============================================================**
2023-05-10 11:53:05,434 MainThread ERROR [root.run:391] 1 Got Exception during acquiring. {'src': 'tk', 'target': 'i', 'task_action': 'UPDATE', 'task_cfg': [{'acquire_type': 'Profile', 'api': 'TK1', 'interval': [2, 3], 'sub_tasks': [{'acquire_type': 'Posts', 'request_limit': {'limit': 100, 'pk_name': 'id'}, 'api': 'TK1'}]}], 'username': 'rdcworld1', 'acquirer_id': 't-37FBD0-tk'}
Traceback (most recent call last):
Error 2)

2023-05-10 11:52:21,353 MainThread INFO [root.get_data:315] response: 200
2023-05-10 11:52:21,353 MainThread ERROR [root.get_data:344] TikTok response: 200, 
2023-05-10 11:52:21,353 MainThread ERROR [root.check_response:51] TickTok EmptyResponseError
Traceback (most recent call last):
  File "/home/ubuntu/ups/acquisition/api/tiktok/__init__.py", line 34, in check_response
    return f(**kv)
  File "/home/ubuntu/ups/acquisition/api/tiktok/TikTokApi/tiktok.py", line 610, in user_posts_page
    res = self.get_data(url=api_url, send_tt_params=True, **kwargs)
  File "/home/ubuntu/ups/acquisition/api/tiktok/TikTokApi/tiktok.py", line 348, in get_data
    ) from None
acquisition.api.tiktok.TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://t.tiktok.com/api/post/item_list/?aid=1988&app_name=tiktok_web&channel=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&re

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 5.0.0] - if out of date upgrade before posting an issue

**Additional context**

**Comment by meet-cipio** [comment]
@davidteather

**Comment by davidteather** [comment]
Should be fixed in V6
