### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by dortesy** [davidteather/TikTok-Api#1031]
Someone experiencing the same problem with video api? Can't get info of video becuase api is giving empty page

Traceback (most recent call last):
  File "E:\tiktok\s.py", line 94, in <module>
    data = video.info()
  File "E:\tiktok\venv\lib\site-packages\TikTokApi\api\video.py", line 74, in info
    return self.info_full(**kwargs)["itemInfo"]["itemStruct"]
  File "E:\tiktok\venv\lib\site-packages\TikTokApi\api\video.py", line 95, in info_full
    return self.parent.get_data(path, **kwargs)
  File "E:\tiktok\venv\lib\site-packages\TikTokApi\tiktok.py", line 384, in get_data
    raise EmptyResponseException(0, None,

TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://m.tiktok.com/api/item/detail/?aid=1988

**Comment by Kresys** [comment]
Found a solution here https://github.com/davidteather/TikTok-Api/issues/1024#issuecomment-1640020587

**Comment by dortesy** [comment]
> Found a solution here [#1024 (comment)](https://github.com/davidteather/TikTok-Api/issues/1024#issuecomment-1640020587)

I tried this method still does not work

**Comment by 419606974** [comment]
same issue

**Comment by davidteather** [comment]
Probably fixed in V6
