### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by tobywcj** [davidteather/TikTok-Api#1034]
Fill Out the template :)

**Describe the bug**

The hashtag search is returning an error.

**The buggy code**

# import the tiktok python SDK
from TikTokApi import TikTokApi

# get the cookie data
verifyFp = "verify_lkdpdu0h_MP57qy7j_i4VA_4sht_8d8Q_JGHjaKafLOyL"
#  create an instance of the TikTokApi class / test endpoints to hit the non-production endpoints multiple times
with TikTokApi(custom_verifyFp=verifyFp, use_test_endpoints=True) as api:
    # get the hashtag data
    hashtag = api.hashtag(name="python")
    # print the data
    print(hashtag)

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
python tiktok.py                                                                                                                                                   ─╯
Traceback (most recent call last):
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/tiktok.py", line 13, in <module>
    print(hashtag)
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 139, in __str__
    return f"TikTokApi.hashtag(id='{self.id}', name='{self.name}')"
                                    ^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 144, in __getattr__
    self.as_dict = self.info()
                   ^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 56, in info
    return self.info_full(**kwargs)["challengeInfo"]["challenge"]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 82, in info_full
    data = self.parent.get_data(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/tiktok.py", line 266, in get_data
    ) = asyncio.get_event_loop().run_until_complete(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/browser_utilities/browser.py", line 212, in sign_url
    evaluatedPage = await page.evaluate(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 8662, in evaluate
    await self._impl_obj.evaluate(
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_page.py", line 395, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: TypeError: undefined is not an object (evaluating 'S[A][m(a[oprand[1]],oprand[1])]')

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ──────────────────────────────────────────────────── 1 ✘  TikTokAnalytics   base   05:13:40 PM  ─╮
╰─ pip uninstall playwright                                                                                                                                           ─╯
Found existing installation: playwright 1.36.0
Uninstalling playwright-1.36.0:
  Would remove:
    /Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/bin/playwright
    /Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright-1.36.0.dist-info/*
    /Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/*
Proceed (Y/n)? y
  Successfully uninstalled playwright-1.36.0

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ─────────────────────────────────────────────── ✔  4s   TikTokAnalytics   base   05:17:14 PM  ─╮
╰─ python3 -m playwright install                                                                                                                                      ─╯
/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/bin/python3: No module named playwright

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ──────────────────────────────────────────────────── 1 ✘  TikTokAnalytics   base   05:17:36 PM  ─╮
╰─ python -m playwright install                                                                                                                                       ─╯
/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/bin/python: No module named playwright

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ──────────────────────────────────────────────────── 1 ✘  TikTokAnalytics   base   05:18:03 PM  ─╮
╰─ python uninstall TikTokApi                                                                                                                                         ─╯
python: can't open file '/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/uninstall': [Errno 2] No such file or directory

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ──────────────────────────────────────────────────── 2 ✘  TikTokAnalytics   base   05:18:29 PM  ─╮
╰─ pip install playwright                                                                                                                                             ─╯
Collecting playwright
  Obtaining dependency information for playwright from https://files.pythonhosted.org/packages/ef/ed/1387012c1e98e604212cff24a789452c0408fb12c6a4a323f4bc571e140d/playwright-1.36.0-py3-none-macosx_11_0_arm64.whl.metadata
  Downloading playwright-1.36.0-py3-none-macosx_11_0_arm64.whl.metadata (3.5 kB)
Requirement already satisfied: greenlet==2.0.2 in ./TikTokAnalytics/lib/python3.11/site-packages (from playwright) (2.0.2)
Requirement already satisfied: pyee==9.0.4 in ./TikTokAnalytics/lib/python3.11/site-packages (from playwright) (9.0.4)
Requirement already satisfied: typing-extensions in ./TikTokAnalytics/lib/python3.11/site-packages (from pyee==9.0.4->playwright) (4.7.1)
Using cached playwright-1.36.0-py3-none-macosx_11_0_arm64.whl (31.3 MB)
Installing collected packages: playwright
Successfully installed playwright-1.36.0

╭─    ~/L/Cl/G/My Drive/Projects/TikTok Data Analytics App ─────────────────────────────────────────────── ✔  4s   TikTokAnalytics   base   05:18:45 PM  ─╮
╰─ python tiktok.py                                                                                                                                                   ─╯
Traceback (most recent call last):
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/tiktok.py", line 13, in <module>
    print(hashtag)
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 139, in __str__
    return f"TikTokApi.hashtag(id='{self.id}', name='{self.name}')"
                                    ^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 144, in __getattr__
    self.as_dict = self.info()
                   ^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 56, in info
    return self.info_full(**kwargs)["challengeInfo"]["challenge"]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/api/hashtag.py", line 82, in info_full
    data = self.parent.get_data(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/tiktok.py", line 266, in get_data
    ) = asyncio.get_event_loop().run_until_complete(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/TikTokApi/browser_utilities/browser.py", line 212, in sign_url
    evaluatedPage = await page.evaluate(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 8662, in evaluate
    await self._impl_obj.evaluate(
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_page.py", line 395, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/toby/Library/CloudStorage/GoogleDrive-tobywong42r@gmail.com/My Drive/Projects/TikTok Data Analytics App/TikTokAnalytics/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: TypeError: undefined is not an object (evaluating 'S[A][m(a[oprand[1]],oprand[1])]')

**Expected behavior**

I expected the hashtag search to return a list of hashtag objects.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - TikTokApi Version 5.2.2

**Additional context**

**Comment by Vanilla-Mix** [comment]
Hey I'm getting something similar on the bottom but mine says:

playwright._impl._api_types.Error: TypeError: undefined is not an object (evaluating 'S[A][m(a[oprand[1]],oprand[1])]')

**Comment by tobywcj** [comment]
@gradill22 thank you so much!!!

**Comment by davidteather** [comment]
Probably fixed in V6
