### ISSUE TITLE
[BUG] - api.search.videos not working

### ISSUE THREAD

**Issue by dortesy** [davidteather/TikTok-Api#1039]
api.search.videos is not working in new version of TikTok-Api? Is search only works for users?

**Comment by impactcolor** [comment]
did you find a solution? @dortesy

**Comment by zakrian07** [comment]
its buggy only work with users sometime it works for me singhera@singhera:~/projects/tokbackup/tiktok-transcript-backend/TikTok-Api/examples$ python3 video_example.py 
An error occurred:
Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.tiktok.com/", waiting until "load"
============================================================
singhera@singhera:~/projects/tokbackup/tiktok-transcript-backend/TikTok-Api/examples$ python3 user_example.py 
Traceback (most recent call last):
  File "/home/singhera/projects/tokbackup/tiktok-transcript-backend/TikTok-Api/examples/user_example.py", line 26, in <module>
    asyncio.run(user_example())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/singhera/projects/tokbackup/tiktok-transcript-backend/TikTok-Api/examples/user_example.py", line 15, in user_example
    await api.create_sessions(proxies=[proxy_config], ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
  File "/home/singhera/.local/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 237, in create_sessions
    await asyncio.gather(
  File "/home/singhera/.local/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 171, in __create_session
    await page.goto(url)
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9135, in goto
    await self._impl_obj.goto(
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 491, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/home/singhera/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.tiktok.com/", waiting until "load"
============================================================
singhera@singhera:~/projects/tokbackup/tiktok-transcript-backend/TikTok-Api/examples$ python3 user_example.py 

 plz advise @davidteather

**Comment by davidteather** [comment]
Seems like you need to be logged in to do api.search.videos and to see videos on tiktok.com so it might work if you log in on tiktok.com then provide the logged in cookies but not officially supported bc this is fully unauthenticated requests

**Comment by zakrian07** [comment]
Ok can we login with api ?
I feel the timeout issue still coming with username as well some time
Some time work some time not
Even I’m using bright data scrapping proxy

**Comment by davidteather** [comment]
Would need actual code samples to see if error is coming from users in general. Tests don't have this error so might be the code's issue?

**Comment by zakrian07** [comment]
I’m using same example code v6 latest code
