### ISSUE TITLE
TikTok-Api does not work at all

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#106]
Every example script yields an error

Traceback (most recent call last):
  File "test1.py", line 7, in <module>
    tiktoks = api.byUsername('americanredcross', count=count)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 125, in byUsername
    data = self.getUserObject(username)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 238, in getUserObject
    b = browser(api_url)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py", line 27, in __init__
    asyncio.get_event_loop().run_until_complete(self.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py", line 30, in start
    self.browser = await pyppeteer.launch(self.options)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

Ubuntu 18.04.4 LTS

**Comment by davidteather** [comment]
#95
