### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#110]
Traceback (most recent call last):
  File "slurp_hash.py", line 12, in <module>
    tiktoks = api.byHashtag('beforeafter', count=count, start=start)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 176, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 215, in getHashtagObject
    b = browser(api_url)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py", line 27, in __init__
    asyncio.get_event_loop().run_until_complete(self.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py", line 55, in start
    }''')
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/page.py", line 1184, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/frame_manager.py", line 309, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/execution_context.py", line 54, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/execution_context.py", line 113, in evaluateHandle
    helper.getExceptionMessage(exceptionDetails)))
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property '1' of undefined
    at __pyppeteer_evaluation_script__:3:74

If I understand it correctly, it means that TikTok blocked my IP to https://m.tiktok.com/api/challenge/detail/?verifyFP=&challengeName={}&language=en. Please correct me if I'm missing something

**Comment by davidteather** [comment]
Yeah I’m fairly sure it’s from tiktok blocking your ip. If tiktok is available in your country you might want to add delays between requests to the api to increase your odds this won’t happen.

**Comment by davidteather** [comment]
I’ll look more into this in a few hours

**Comment by roshansathya** [comment]
Thanks @davidteather.
![image](https://user-images.githubusercontent.com/34704549/83775916-28a5f180-a6a5-11ea-961e-669391cd6baa.png)

**Comment by dj2ball** [comment]
Likewise, think the signature was updated as this just universally stopped working when I wasn't even scraping.

**Comment by Daryl149** [comment]
Same issue since the last 3 hours on 3 different instances (2 at AWS (Asia) and 1 at Digital Ocean (US) ).

**Comment by davidteather** [comment]
I've issued a fix upgrade your package version.
```
pip install TikTokApi --upgrade
```
