### ISSUE TITLE
[INSTALLATION] - TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by kulig1985** [davidteather/TikTok-Api#1102]
Try to run the docker command with the original trending example and got this error:

Traceback (most recent call last):
  File "/TikTokApi/trending_example.py", line 1, in <module>
    from TikTokApi import TikTokApi
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/__init__.py", line 1, in <module>
    from TikTokApi.tiktok import TikTokApi
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 41, in <module>
    class TikTokApi:
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 197, in TikTokApi
    ms_tokens: list[str] = None,
TypeError: 'type' object is not subscriptable

this is the docker command i run:

docker run -v /host_path_to_api/examples:/TikTokApi -e ms_token=my_ms_token --rm tiktokapi:latest python3 /TikTokApi/trending_example.py

**Comment by Vinlow** [comment]
+1

**Comment by ChocoTonic** [comment]
you need to be 3.9 minimum. odd the dockerfile doesn't specify this

**Comment by fabgrd** [comment]
Same issue, my version is 3.12 and I tried everything..

**Comment by belaboe97** [comment]
Answer of @ChocoTonic worked for me! 

Tested locally with trending_example. I just changed the Dockerfile to: 

```
FROM mcr.microsoft.com/playwright:focal
FROM python:3.10-slim

RUN apt-get update && apt-get install -y python3-pip


COPY . .
RUN pip3 install TikTokApi
RUN python3 -m playwright install
RUN playwright install-deps
```
