### ISSUE TITLE
Hashtags and unicode

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#116]
I've tried to fetch russian hashtag селфи and got error

Traceback (most recent call last):
  File "slurp_hash.py", line 17, in <module>
    tiktoks = api.byHashtag(tag, count=count, start=start)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 188, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 224, in getHashtagObject
    return self.getData(api_url, b.signature, b.userAgent)
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 44, in getData
    'accept-language': 'en-US,en;q=0.9'
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1305, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.6/http/client.py", line 1237, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 47-51: ordinal not in range(256)

Looks like hashtag should be urlencoded.

**Comment by davidteather** [comment]
Update your TikTokApi with
```
pip install TikTokApi --upgrade
```

New release has fixed this.

**Comment by aspi632** [comment]
> I've tried to fetch russian hashtag селфи and got error

Hi, man, I probably have the same issue trying to work with russian hashtags, but the error message is different:
_KeyError: 'challengeInfo'_
I downloaded the last version and it still got the same error.
Can you please share the part of your code with hashtag coding and byHashtag() method?
Thank you!

**Comment by davidteather** [comment]
TikTok changed their servers to actually handle utf-8 code correctly before they were doing it kinda dumb. So, I've updated it to match their servers. There will be a new release within 30 minutes

**Comment by aspi632** [comment]
Wow, that's great!
Thank you so much :)
