### ISSUE TITLE
[BUG] Page.evaluate: ReferenceError: opts is not defined

### ISSUE THREAD

**Issue by pstemporowski** [davidteather/TikTok-Api#1169]
**Describe the bug**
The issue is quite simple: I cannot create an TikTok-API session on macOS. When I run the same code on Ubuntu, it works perfectly. Additionally, it was working fine on macOS yesterday as well.

The crash occurs when trying to create the session, with the error indicating that userAgent is not defined. However, when I run the same line that crashes in my main, it correctly shows my userAgent, and the copied code does not crash.

**The buggy code**
```py
import asyncio
import logging
import os
from TikTokApi import TikTokApi
import dotenv
from playwright.async_api import async_playwright

dotenv.load_dotenv()

ms_token = os.environ.get("ms_token", None)


# ONLY FOR DEBUGGING PLAYWRIGHT
async def set_session_params(session):
    user_agent = await session.page.evaluate("() => navigator.userAgent")
    print(f"User Agent: {user_agent}")


async def main():
    # ONLY FOR DEBUGGING PLAYWRIGHT
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        context = await browser.new_context()
        page = await context.new_page()

        session = type("", (), {})()  # Create a dummy session object
        session.page = page

        await set_session_params(session)

        await browser.close()

    # The Actual Code
    async with TikTokApi(logging_level=logging.DEBUG, logger_name="tiktokapi") as api:
        print("Creating Session...")
        await api.create_sessions(
            ms_tokens=[ms_token], num_sessions=1, sleep_after=10, headless=False
        )
        print("Created Session")
        async for video in api.trending.videos(count=30):
            print(video)
            print(video.as_dict)


if __name__ == "__main__":
    asyncio.run(main())
```

**Expected behavior**
It should create the TikTok session

** Output of my code **

```
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/127.0.6533.17 Safari/537.36
Creating Session...
Traceback (most recent call last):
  File "/Users/pstemporowski/dev/playground/test-tiktokapi/main.py", line 45, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/pstemporowski/dev/playground/test-tiktokapi/main.py", line 35, in main
    await api.create_sessions(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 260, in create_sessions
    await asyncio.gather(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 201, in __create_session
    await self.__set_session_params(session)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 94, in __set_session_params
    user_agent = await session.page.evaluate("() => navigator.userAgent")
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8340, in evaluate
    await self._impl_obj.evaluate(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/playwright/_impl/_page.py", line 440, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 278, in evaluate
    await self._channel.send(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crypto-copy-cat-bot/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.evaluate: ReferenceError: opts is not defined
    at Navigator.get [as userAgent] (<anonymous>:11:42)
    at eval (eval at evaluate (:226:30), <anonymous>:1:17)
    at UtilityScript.evaluate (<anonymous>:233:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

**Desktop (please complete the following information):**
 - OS: MacOs 
 - TikTokApi Versio: 6.3.0

**Additional context**

**Comment by pstemporowski** [comment]
Closing the issue because the comment https://github.com/davidteather/TikTok-Api/issues/1012#issuecomment-1607264627 resolved it for me. The latest version of Playwright likely addressed the problem.

**Comment by FabrizioMazzucco** [comment]
Hi i have the same problem, i test with distinct versions for playwright, requests and tiktok api and have the error. Can you tell me what are your versions for this libraries please?

**Comment by pstemporowski** [comment]
Hi,

I'm using:
python 3.10
tiktok api 6.5.2
playwright 1.37
