### ISSUE TITLE
[BUG] - TikTokApi.exceptions.EmptyResponseException: None -> TikTok returned an empty response

### ISSUE THREAD

**Issue by obscure723** [davidteather/TikTok-Api#1188]
**Describe the bug**
The TikTokApi is returning an empty response when trying to fetch user information, resulting in an EmptyResponseException.

**The buggy code**
```py
import logging
from TikTokApi import TikTokApi
import asyncio

TikTokApi(logging_level=logging.INFO)  # SETS LOGGING_LEVEL TO INFO

async def user_example2():
    async with TikTokApi() as api:
        await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
        user = api.user("therock")
        user_data = await user.info()
        print(user_data)

        async for video in user.videos(count=30):
            print(video)
            print(video.as_dict)

        async for playlist in user.playlists():
            print(playlist)

def job():
    asyncio.run(user_example2())

if __name__ == "__main__":
    job()
```

**Expected behavior**
The code should fetch and print user information, videos, and playlists for the user "therock".

**Error Trace (if any)**
```
Traceback (most recent call last):
  File "/app/main.py", line 1033, in <module>
    job()
  File "/app/main.py", line 1021, in job
    asyncio.run(user_example2())
  File "/usr/local/lib/python3.9/dist-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
  File "/usr/local/lib/python3.9/dist-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/app/main.py", line 1009, in user_example2
    user_data = await user.info()
  File "/usr/local/lib/python3.9/dist-packages/TikTokApi/api/user.py", line 76, in info
    resp = await self.parent.make_request(
  File "/usr/local/lib/python3.9/dist-packages/TikTokApi/tiktok.py", line 451, in make_request
    raise EmptyResponseException(result, "TikTok returned an empty response")
TikTokApi.exceptions.EmptyResponseException: None -> TikTok returned an empty response
```

**Desktop (please complete the following information):**
 - OS: macOS (M1 Mac)
 - TikTokApi Version: 6.4.0

**Additional context**
- The error occurs when trying to fetch user information using `user.info()`. The API is returning an empty response, which is causing an EmptyResponseException to be raised. This prevents the rest of the code (fetching videos and playlists) from executing.
- The `ms_token` is obtained from the user's own browser.
- The issue is occurring on an M1 Mac, which might potentially affect the behavior due to the different architecture.

**Comment by itsEricWu** [comment]
+1

**Comment by wpz5159582** [comment]
+1

**Comment by moonzlo** [comment]
+1

**Comment by Gereks123** [comment]
Check out this open issue, might help you resolve the issue! https://github.com/davidteather/TikTok-Api/issues/1179#issuecomment-2315970181

**Comment by obscure723** [comment]
thank you.I will review this open issue.


> Check out this open issue, might help you resolve the issue! [#1179 (comment)](https://github.com/davidteather/TikTok-Api/issues/1179#issuecomment-2315970181)

**Comment by zakrian07** [comment]
this is not working solution
