### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Inzilkin** [davidteather/TikTok-Api#124]
**Describe the bug**

After ~ 30 seconds, such an error occurs. Everything is fine on my computer, but unfortunately an error occurs on the server

**The buggy code**

Traceback (most recent call last):
  File "tt_api_check.py", line 6, in <module>
    trending = api.trending(count=30)
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/tiktok.py", line 84, in                                                                                                                      trending
    b = browser(api_url, language=language)
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/browser.py", line 34, i                                                                                                                     n __init__
    loop.run_until_complete(self.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_compl                                                                                                                     ete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/browser.py", line 37, i                                                                                                                     n start
    self.browser = await pyppeteer.launch(self.options)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 305,                                                                                                                      in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 166,                                                                                                                      in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 225,                                                                                                                      in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Expected behavior**

Used api.trending(count=30)

**Screenshots**

[click to view screenshot](https://imgur.com/a/PXuIMeh)

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu 19.10)

**Additional context**

This error only appears on my servers. I tried on two, the error remains. Used the code from the example [click](https://github.com/davidteather/TikTok-Api/blob/master/examples/getTrending.py)

**Comment by davidteather** [comment]
#95
