### ISSUE TITLE
[BUG] - script is unstable

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#169]
I was running my script on one server with decent stability; moved it to different one and got it totally unstable.

The error is always 

`(tiktok) tarkhil@Blade9:~/tiktok$ python spider_v.py
2020-07-06 22:32:45.631072 loading 6557545354023698433
Traceback (most recent call last):
  File "spider_v.py", line 58, in <module>
    res = api.userPosts( userID, secUID, count=3000 )
  File "/home/tarkhil/.local/share/virtualenvs/tiktok-80xSTSAj/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 120, in userPosts
    res = self.getData(api_url, b, proxy=proxy)
  File "/home/tarkhil/.local/share/virtualenvs/tiktok-80xSTSAj/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 30, in getData
    "&_signature=" + b.signature
AttributeError: 'browser' object has no attribute 'verifyFp'
`
Code samples for pyppeteer runs fine. ulimit seems to be enough.

**Comment by davidteather** [comment]
See #166
