### ISSUE TITLE
Converting response to JSON failed response is below (probably empty)

### ISSUE THREAD

**Issue by soleimanian** [davidteather/TikTok-Api#210]
Hi,
I get this error when running "getTiktoksByHashtag" on windows server 2012.
But is is OK on windows 10.
I use same Python and TikTokApi version.
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 48, in getData
    return r.json()
  File "C:\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\examples\getTiktoksByHashtag.py", line 7, in <module>
    tiktoks = api.byHashtag('viral', count=count)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 255, in byHashtag
    res = self.getData(api_url, b, proxy=proxy, language=language)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 54, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response
```

**Comment by markdrrr** [comment]
I get the same error when I call the method
 api = TikTokApi() 
tiktoks = api.byUsername('nick')

**Comment by davidteather** [comment]
See #207
