### ISSUE TITLE
[BUG] - ByHashtag Not Working

### ISSUE THREAD

**Issue by soleimanian** [davidteather/TikTok-Api#213]
I run the bytag code and get the below error.
I have installed chromedriver and works properly.

{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.0 Safari/537.36)', 'accept-encoding': 'gzip, deflate, br', 'accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'authority': 'm.tiktok.com', 'method': 'GET', 'path': '/share/item/list?secUid=&id=5054&type=3&count=50&minCursor=0&maxCursor=0&shareUid=&lang=en&verifyFp=WWdzPV1IIfynsEDN&_signature=_02B4Z6wo00f01dpc3OQAAIBAiIevIjiGAd3aXNhAACmo7e', 'scheme': 'https', 'accept-language': 'en-US,en;q=0.9', 'referrer': 'https://www.tiktok.com/', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-site'}
Converting response to JSON failed response is below (probably empty)

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 48, in getData
    return r.json()
  File "C:\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\getbytag.py", line 41, in <module>
    Hashtag= api.byHashtag(tag, count=count)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 255, in byHashtag
    res = self.getData(api_url, b, proxy=proxy, language=language)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 54, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response

**Comment by davidteather** [comment]
I made a fix on the nightly branch right now. They've also changed a few other endpoints which I'll be fixing before pushing a release

**Comment by davidteather** [comment]
Fixed in most recent release
