### ISSUE TITLE
[BUG] - ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by fifty59nine** [davidteather/TikTok-Api#223]
Code under is returning error: ConnectionResetError: [WinError 10054] Remote host forcibly terminated existing connection

**CODE:**
```
import TikTokApi

api = TikTokApi.TikTokApi()
url = 'https://www.tiktok.com/@august_yan/video/6856392294505942274'

x = api.get_Video_No_Watermark(url)
print(x)
```

**CONSOLE LOG:**
```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Den4ik\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Den4ik\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
https://api.tiktokv.com/aweme/v1/playwm/?video_id=&line=0&ratio=default&media_type=4&vr_type=0
https://api.tiktokv.com/aweme/v1/playwm/?video_id=&line=0&ratio=default&media_type=4&vr_type=0
```

**Comment by davidteather** [comment]
Video was posted after the end of July. 
For more information #203
