### ISSUE TITLE
[BUG] - AttributeError: 'browser' object has no attribute 'verifyFp'

### ISSUE THREAD

**Issue by fastandslow007** [davidteather/TikTok-Api#255]
Noticed error on getting content byHashtag. Error message thrown: "AttributeError: 'browser' object has no attribute 'verifyFp'"

```
Traceback (most recent call last):
  File "/home/tiktok/tiktok.py", line 245, in <module>
    tk_agent.start()
  File "/home/tiktok/tiktok.py", line 221, in start
    self.by_hashtag(hashtag=tag, count=self.post_per_request)
  File "/home/tiktok/tiktok.py", line 125, in by_hashtag
    posts = self.api.byHashtag(hashtag=hashtag, count=count, language='en')
  File "/home/tiktok/.venv/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 466, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "/home/tiktok/.venv/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 516, in getHashtagObject
    return self.getData(b, proxy=proxy)
  File "/home/tiktok/.venv/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 70, in getData
    query = {'verifyFp': b.verifyFp, 'did': b.did, '_signature': b.signature}
AttributeError: 'browser' object has no attribute 'verifyFp'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/tiktok/.venv/lib/python3.6/site-packages/pyppeteer/launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/tiktok/.venv/lib/python3.6/site-packages/pyppeteer/launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

The code suspected the problem, tiktok.py around line 70:
```
 55     def getData(self, b, language='en', proxy=None) -> dict:
 56         """Returns a dictionary of a response from TikTok.
 57
 58           :param api_url: the base string without a signature
 59
 60           :param b: The browser object that contains the signature
 61
 62           :param language: The two digit language code to make requests to TikTok with.
 63                            Note: This doesn't seem to actually change things from the API.
 64
 65           :param proxy: The IP address of a proxy server to request from.
 66         """
 67         if self.request_delay is not None:
 68             time.sleep(self.request_delay)
 69
 70         query = {'verifyFp': b.verifyFp, 'did': b.did, '_signature': b.signature}
 71         url = "{}&{}".format(b.url, urlencode(query))
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0
 - TikTokApi Version TikTokApi==3.4.7

**Comment by davidteather** [comment]
There’s a ton of closed and I think one open issues for the same issue please refer to them to see if your issue is solved by it. Start with the closed issues
