### ISSUE TITLE
getTikTokById not returning anything

### ISSUE THREAD

**Issue by Coloradohusky** [davidteather/TikTok-Api#280]
**Describe the bug**

Running my program, [TikUp](https://github.com/Coloradohusky/TikUp), with any ID, user, etc. returns the error shown below.

**The buggy code**

Looks like it's happening with `api.getTikTokById(tiktokId)`.

**Expected behavior**

It should return a TikTok object

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
C:\Users\Coloradohusky>tikup --id 6850191098153946374
{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36', 'accept-encoding': 'gzip, deflate, br', 'accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'authority': 'm.tiktok.com', 'method': 'GET', 'path': '/api/item/detail/?aid=1988&app_name=tiktok_web&device_platform=web&Referer=&user_agent=Mozilla%252F5.0%2B%28Windows%2BNT%2B10.0%253B%2BWin64%253B%2Bx64%29%2BAppleWebKit%252F537.36%2B%28KHTML%2C%2Blike%2BGecko%29%2BChrome%252F84.0.4147.125%2BSafari%252F537.36&cookie_enabled=true&screen_width=800&screen_height=600&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&itemId=6850191098153946374&lang=en&verifyFp=YUuqSB9xXb6v9wze&did=438336499&_signature=_02B4Z6wo00f01Vp6sMAAAIBCMSCKA1-h.mlaerRAAAnu6f', 'scheme': 'https', 'accept-language': 'en-US,en;q=0.9', 'referer': 'https://www.tiktok.com/', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-site', 'cookie': 'tt_webid_v2=438336499'}
Converting response to JSON failed response is below (probably empty)

Traceback (most recent call last):
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 89, in getData
    return r.json()
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Coloradohusky\AppData\Local\Programs\Python\Python38\Scripts\tikup.exe\__main__.py", line 7, in <module>
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 210, in main
    tiktoks = downloadTikToks(username, tiktoks, file, downloadType)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 134, in downloadTikToks
    tiktokObj = getTikTokObject(tiktok)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\tikup\tikup.py", line 167, in getTikTokObject
    thing = api.getTikTokById(tiktokId)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 640, in getTikTokById
    return self.getData(b, proxy=proxy)
  File "c:\users\coloradohusky\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 97, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response
```

**Desktop (please complete the following information):**
 - Windows 10
 - TikTokApi Version 3.5.2

**Additional context**

Visiting the TikTok website still works fine. Clearing cookies from Chrome didn't do anything.

**Comment by davidteather** [comment]
It seems to be working for my network. The issue may arise if you're making too many requests.

```
TikTokApi(debug=False, request_delay=None, executablePath=None)
```
You can pass the request_delay if it continues to be a problem.

**Comment by Coloradohusky** [comment]
Yeah, that's what I thought, thanks! Just wanted to make sure there wasn't anything actually wrong
