### ISSUE TITLE
DownloadTiktok.py Example is not working

### ISSUE THREAD

**Issue by DonPepeSun** [davidteather/TikTok-Api#284]
With any url video, it has an exception :

Traceback (most recent call last):
  File "c:/Users/User/Desktop/runing_example.py", line 6, in <module>
    tiktokData = api.get_Video_By_Url("https://www.tiktok.com/@user/video/000example000", return_bytes=1)
  File "C:\Python\lib\site-packages\TikTokApi\tiktok.py", line 909, in get_Video_By_Url
    raise Exception("Deprecated. Other Methods Work Better.")
Exception: Deprecated. Other Methods Work Better.

**Comment by davidteather** [comment]
Delete line 6
