### ISSUE TITLE
[BUG] - Invalid response

### ISSUE THREAD

**Issue by bengisupinar** [davidteather/TikTok-Api#287]
Output:
Expecting value: line 1 column 1 (char 0)
{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36', 'accept-encoding': 'gzip, deflate, br', 'accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'authority': 'm.tiktok.com', 'method': 'GET', 'path': '/api/user/detail/?aid=1988&app_name=tiktok_web&device_platform=web&referer=https%3A%2F%2Fwww.', 'scheme': 'https', 'accept-language': 'en-US,en;q=0.9', 'referer': 'https://www.tiktok.com/', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-site', 'cookie': 'tt_webid_v2=883178708'}
Converting response to JSON failed response is below (probably empty)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 91, in getData
    return r.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alm.py", line 139, in <module>
    tt_follower = tiktok_a()
  File "alm.py", line 100, in tiktok_a
    user_ = api.getUser(username)
  File "/usr/local/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 725, in getUser
    return self.getData(b, proxy=proxy)
  File "/usr/local/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 99, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

--There is no block for outgoing connections in firewall, I checked that.

Code:
```
    set_async()
    time.sleep(30)
    api = TikTokApi(debug=True, executablePath = '/usr/bin/chromium-browser')
    time.sleep(30)
    username = 'puhutv'
    user_ = api.getUser(username)

 - OS: Ubuntu

**Comment by amoghden** [comment]
I'm having this same issue. Any solutions?
