### ISSUE TITLE
[INSTALLATION] - error when collecting playwright

### ISSUE THREAD

**Issue by wying8349** [davidteather/TikTok-Api#351]
**When I try to upgrade TikTokApi, the following error occurs:**

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
    local_file = unpack_url(
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url
    file = get_http_url(
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url
    from_path, content_type = _download_http_url(
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 282, in _download_http_url
    for chunk in download.chunks:
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 168, in iter
    for x in it:
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 64, in response_chunks
    for chunk in response.raw.stream(
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/wying/.local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Desktop:**
 - OS: Ubuntu

**Comment by everestpipkin** [comment]
Possibly related - (Mac OS 10.13) playwright and pyppeteer demand different (incompatible) versions of pyee.

playwright 0.152.0 has requirement pyee>=8.0.1, but you'll have pyee 7.0.4 which is incompatible.
pyppeteer 0.2.2 has requirement pyee<8.0.0,>=7.0.1, but you'll have pyee 8.1.0 which is incompatible.

**Comment by wying8349** [comment]
> Possibly related - (Mac OS 10.13) playwright and pyppeteer demand different (incompatible) versions of pyee.
> 
> playwright 0.152.0 has requirement pyee>=8.0.1, but you'll have pyee 7.0.4 which is incompatible.
> pyppeteer 0.2.2 has requirement pyee<8.0.0,>=7.0.1, but you'll have pyee 8.1.0 which is incompatible.

This is possible. I'll try to install them separately.

**Comment by jp-wagner** [comment]
> playwright 0.152.0 has requirement pyee>=8.0.1, but you'll have pyee 7.0.4 which is incompatible.
> pyppeteer 0.2.2 has requirement pyee<8.0.0,>=7.0.1, but you'll have pyee 8.1.0 which is incompatible.

Same issue. Did you end up finding a fix?

**Comment by wying8349** [comment]
I re-installed the whole project in a fresh VM. I am successful when installing, but when I tried to run the example getTrending I have the following error trace:
```
Traceback (most recent call last):
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/browser_type.py", line 69, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Failed to launch webkit because executable doesn't exist at /home/wying/.cache/ms-playwright/webkit-1347/pw_run.sh
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wying/Desktop/TikRes/TikTok-Api-master/examples/getTrending.py", line 4, in <module>
    api = TikTokApi.get_instance()
  File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/tiktok.py", line 76, in get_instance
    TikTokApi(**kwargs)
  File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/tiktok.py", line 42, in __init__
    self.browser = browser(**kwargs)
  File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/browser.py", line 78, in __init__
    raise e
  File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/browser.py", line 76, in __init__
    self.browser = get_playwright().webkit.launch(args=self.args, **self.options)
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_api.py", line 6142, in launch
    self._sync(
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/browser_type.py", line 72, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

ERROR:asyncio:Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at /home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at /home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py:100>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py", line 101, in callback
    g_self.switch()
greenlet.GreenletExit
```

**Comment by jp-wagner** [comment]
yes, same thing I'm getting. I suspected it was because of the conflicting requirements like everestpipkin said.

**Comment by jp-wagner** [comment]
Ok, as far as I can tell the issue for me is that playwright requires the libicu66 package while my Arch installation runs with libicu67. Unfortunately, I can't downgrade as it would break a bunch of dependencies. As of now, I don't have a fix for this.

**Comment by wying8349** [comment]
I tried a windows system and this occurs for me on windows 10 as well. The error says
```
ERROR: pyppeteer 0.2.2 has requirement pyee<8.0.0,>=7.0.1, but you'll have pyee 8.1.0 which is incompatible.
```

**Comment by davidteather** [comment]
Try to use a virtual environment for python

**Comment by wying8349** [comment]
I am getting the same error in the venv (in windows system).

**Comment by davidteather** [comment]
If you want I've started maintaining a pyppeteer fork [here](https://github.com/TikTokApi-Pyppeteer/TikTok-Api-Pyppeteer)

**Comment by jp-wagner** [comment]
Yes, already checked it out @davidteather. Thanks a lot for maintaining a non playwright version since it doesn't seem like they're going to support Arch anytime soon. For me the issue is closed!

**Comment by dylancaponi** [comment]
@davidteather What's the proper way to implement the TikTokApi-pyppeteer fork?

Installing with: `pip install TikTokApi-pyppeteer` and importing with `from TikTokApi import TikTokApi`
causes: `ModuleNotFoundError: No module named 'TikTokApi'`

**Comment by mengguiyouziyi** [comment]
> I re-installed the whole project in a fresh VM. I am successful when installing, but when I tried to run the example getTrending I have the following error trace:
> 
> ```
> Traceback (most recent call last):
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/browser_type.py", line 69, in launch
>     return from_channel(await self._channel.send("launch", params))
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/connection.py", line 39, in send
>     result = await callback.future
> playwright.helper.Error: Failed to launch webkit because executable doesn't exist at /home/wying/.cache/ms-playwright/webkit-1347/pw_run.sh
> Try re-installing playwright with "npm install playwright"
> Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/wying/Desktop/TikRes/TikTok-Api-master/examples/getTrending.py", line 4, in <module>
>     api = TikTokApi.get_instance()
>   File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/tiktok.py", line 76, in get_instance
>     TikTokApi(**kwargs)
>   File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/tiktok.py", line 42, in __init__
>     self.browser = browser(**kwargs)
>   File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/browser.py", line 78, in __init__
>     raise e
>   File "/home/wying/Desktop/TikRes/TikTok-Api-master/TikTokApi/browser.py", line 76, in __init__
>     self.browser = get_playwright().webkit.launch(args=self.args, **self.options)
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_api.py", line 6142, in launch
>     self._sync(
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py", line 107, in _sync
>     return future.result()
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/browser_type.py", line 72, in launch
>     raise not_installed_error(f'"{self.name}" browser was not found.')
> Exception: 
> ================================================================================
> "webkit" browser was not found.
> Please complete Playwright installation via running
> 
>     "python -m playwright install"
> 
> ================================================================================
> 
> ERROR:asyncio:Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at /home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py:100
> handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at /home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py:100>
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
>     self._context.run(self._callback, *self._args)
>   File "/home/wying/.local/lib/python3.8/site-packages/playwright/sync_base.py", line 101, in callback
>     g_self.switch()
> greenlet.GreenletExit
> ```

did you resolve this error?

**Comment by wying8349** [comment]
Thank you very much for maintaining this branch. My error has been resolved. This issue can be closed.

**Comment by alebarquin-tl** [comment]
@wying8349 como lo solucionaste?
