### ISSUE TITLE
[INSTALLATION] - AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by Incher25** [davidteather/TikTok-Api#359]
Hi all,

I try to install the recent version of TikTokApi but I receive the following error:

```
$ python -m playwright install
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/inessa/PythonProjects/environments/check_py3.7/lib/python3.7/site-packages/playwright/__init__.py", line 22, in <module>
    import playwright.helper as helper
  File "/home/inessa/PythonProjects/environments/check_py3.7/lib/python3.7/site-packages/playwright/helper.py", line 38, in <module>
    from typing_extensions import Literal, TypedDict
  File "/home/inessa/PythonProjects/environments/check_py3.7/lib/python3.7/site-packages/typing_extensions.py", line 364, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'

```
Versions of software I use:

OS - Ubuntu 17.10
python 3.7.0a2
pip 9.0.1
setuptools 50.3.2

Thanks for help in advance!

**Comment by Incher25** [comment]
Tried to make fresh install in Vagrant with

Ubuntu 18.04
python 3.7.9
pip               20.2.4
setuptools        50.3.2

and everything works fine.
