### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_set_running_loop'

### ISSUE THREAD

**Issue by mengguiyouziyi** [davidteather/TikTok-Api#365]
**Describe the error**

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

results = 10

trending = api.trending(count=results)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))
```

**Error Trace (if any)**

```
Traceback (most recent call last):
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/browser_type.py", line 69, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Playwright.enable): Browser has been closed.
=========================== logs ===========================
<launching> /search/odin/meng/.cache/ms-playwright/webkit-1347/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=187032
[err] /search/odin/meng/.cache/ms-playwright/webkit-1347/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libvpx.so.6: cannot open shared object file: No such file or directory
<process did exit: exitCode=127, signal=null>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    api = TikTokApi.get_instance()
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 77, in get_instance
    TikTokApi(**kwargs)
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 43, in __init__
    self.browser = browser(**kwargs)
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/TikTokApi/browser.py", line 78, in __init__
    raise e
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/TikTokApi/browser.py", line 76, in __init__
    self.browser = get_playwright().webkit.launch(args=self.args, **self.options)
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/sync_api.py", line 6158, in launch
    firefoxUserPrefs=mapping.to_impl(firefoxUserPrefs),
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/browser_type.py", line 72, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

Exception ignored in: <greenlet.greenlet object at 0x7f4a6fc024d0>
Traceback (most recent call last):
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/main.py", line 92, in <lambda>
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/connection.py", line 128, in run_sync
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/site-packages/playwright/transport.py", line 36, in run_sync
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
  File "/search/odin/meng/anaconda3/envs/tiktok-api/lib/python3.7/asyncio/base_events.py", line 540, in run_forever
AttributeError: 'NoneType' object has no attribute '_set_running_loop'
```

**Desktop (please complete the following information):**
 - OS: centos 7
 - TikTokApi Version 3.7.9

**Additional context**

**Comment by davidteather** [comment]
Your real issue is `playwright.helper.Error: Protocol error (Playwright.enable): Browser has been closed.` not sure if playwright is supported on centos at the moment
