### ISSUE TITLE
[BUG] - TikTokApi.userPosts broken again

### ISSUE THREAD

**Issue by vdemay** [davidteather/TikTok-Api#368]
TikTokApi.userPosts seens to be broken again since this several hours: getData returns an empty response 

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
api.byUsername("willsmith", proxy="xxxxxxxxxxx", custom_verifyFp="xxxxxxxxxxxx")
```

**Error Trace**

```
ERROR:root:Expecting value: line 1 column 1 (char 0)
ERROR:root:Converting response to JSON failed response is below (probably empty)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 163, in getData
    return r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 438, in byUsername
    return self.userPosts(
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 401, in userPosts
    res = self.getData(url=api_url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 170, in getData
    raise Exception("Invalid Response")
Exception: Invalid Response
```

I tried to figure out what wrong with this call (missing param, url changes, UA, etc... or something else) and I did not find anything

Any help would be appreciated

Thanks

**Comment by MegaVasiliy007** [comment]
Hello. I am not good at python, but this request work. And user-agent header of course.
`https://m.tiktok.com/api/item_list/?count=30&id=&maxCursor=0&minCursor=0&sourceType=8&_signature=`

**Comment by vdemay** [comment]
My bad
