### ISSUE TITLE
"webkit" browser was not found.

### ISSUE THREAD

**Issue by Sharkyyy3** [davidteather/TikTok-Api#370]
I installed playwright with the "pip install playwright" command. I get an error on startup.
```
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\browser_type.py", line 77, in launch
    return from_channel(await self._channel.send("launch", params))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Failed to launch webkit because executable doesn't exist at C:\Users\Admin\AppData\Local\ms-playwright\webkit-1383\Playwright.exe
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/vk_clips/pyimod04_certifi.py", line 191, in <module>
    parapa(good_profiles, boss_id, se, lii, lol, work, get_inform_status, is_it_mine, requests, headers, Fore, descriptions, random)
  File "C:\Users\Admin\PycharmProjects\vk_clips\log.py", line 584, in parapa
    dict_data = get_trending_tt_clip(clip_history)
  File "C:\Users\Admin\PycharmProjects\vk_clips\tt.py", line 102, in get_trending_tt_clip
    api = TikTokApi.get_instance()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 77, in get_instance
    TikTokApi(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 43, in __init__
    self.browser = browser(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 78, in __init__
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 76, in __init__
    self.browser = get_playwright().webkit.launch(args=self.args, **self.options)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api.py", line 6436, in launch
    self._sync(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_base.py", line 107, in _sync
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\browser_type.py", line 80, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

ERROR:asyncio:Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...=========\n')>) at C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_base.py:100>
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_base.py", line 101, in callback
    g_self.switch()
greenlet.GreenletExit
```

Trying to install a playwright. I write "python-m playwright install" and get an error.
```
C:\Windows\system32>python -m playwright install
(node:8180) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND playw
right.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:8180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:8180) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```
How can I fix this?

Windows 7
Python 3.8
On PC used corporation proxy

**Comment by kami4ka** [comment]
So, the reason is the inability to install the playwright. Try to install it without proxy or using VPN.

**Comment by Sharkyyy3** [comment]
> So, the reason is the inability to install the playwright. Try to install it without proxy or using VPN.
I tried installing playwright via C:\Windows\system32>pip install git+https://github.com/microsoft/playwright-pyth
on. git has previously set global settings for its proxy server for git. The installation was successful, but when running the code, I encountered the following error:

INFO:root:Class initalized
```
Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/vk_clips/pyimod04_certifi.py", line 191, in <module>
    parapa(good_profiles, boss_id, se, lii, lol, work, get_inform_status, is_it_mine, requests, headers, Fore, descriptions, random)
  File "C:\Users\Admin\PycharmProjects\vk_clips\log.py", line 584, in parapa
    dict_data = get_trending_tt_clip(clip_history)
  File "C:\Users\Admin\PycharmProjects\vk_clips\tt.py", line 102, in get_trending_tt_clip
    api = TikTokApi.get_instance(logging_level=logging.INFO)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 77, in get_instance
    TikTokApi(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 43, in __init__
    self.browser = browser(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 78, in __init__
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 76, in __init__
    self.browser = get_playwright().webkit.launch(args=self.args, **self.options)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 24, in get_playwright
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\browser.py", line 22, in get_playwright
    playwright = sync_playwright().start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\__init__.py", line 34, in sync_playwright
    return SyncPlaywrightContextManager()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\main.py", line 81, in __init__
    self._connection = run_driver()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\main.py", line 76, in run_driver
    return loop.run_until_complete(run_driver_async())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\main.py", line 56, in run_driver_async
    proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1615, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 385, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 881, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

Process finished with exit code 1
```

**Comment by davidteather** [comment]
You can also try
```
api = TikTokApi.get_instance(use_selenium=True)
```

for selenium support if playwright doesn't work
