### ISSUE TITLE
Error when packaging pyinstaller

### ISSUE THREAD

**Issue by Sharkyyy3** [davidteather/TikTok-Api#384]
windows 10 x64
python 3.8.1
pyinstaller 4.0
playwright 0.152.0
TikTokApi 3.7.9

Packing with command "pyinstaller -F main.py"

Traceback при запуске:
Traceback (most recent call last): 
   File "main.py", line 19, in get_playwright 
   File "playwright\__init__.py", line 34, in sync_playwright 
   File "playwright\main.py", line 81, in __init__ 
   File "playwright\main.py", line 76, in run_driver 
   File "asyncio\base_events.py", line 612, in run_until_complete 
   File "playwright\main.py", line 44, in run_driver_async 
   File "playwright\main.py", line 36, in compute_driver_executable 
   File "playwright\path_utils.py", line 23, in get_file_dirname 
AssertionError
[12388] Failed to execute script main

As I understand it, the problem is with playwright. How can it be solved? Thank you in advance!

**Comment by dwight9339** [comment]
Bump

**Comment by davidteather** [comment]
It's got to do something with playwright you could try it with selenium maybe with `api = TikTokApi.get_instance(use_selenium=True)` and remove the playwright package from your installation. You might want to see [this playwright issue](https://github.com/microsoft/playwright-python/issues/204)
