### ISSUE TITLE
[BUG] - byHashtag method playwright error

### ISSUE THREAD

**Issue by wangxy524** [davidteather/TikTok-Api#389]
when I use 'byHashtag' method, and set param 'count = 100', it worked fine. 
but when I set 'count = 500', I get error from **playwright**.

> 
exception: Protocol error (Playwright.createContext): Browser has been closed.
Traceback (most recent call last):
  File "tiktokSpider.py", line 54, in work
    trending = api.byHashtag(hashtag=tag, count=self.page_size, language=lan, proxy=None)
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 825, in byHashtag
    res = self.getData(url=api_url, **kwargs)
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 142, in getData
    verify_fp, did, signature = self.browser.sign_url(**kwargs)
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/TikTokApi/browser.py", line 164, in sign_url
    page = self.create_page()
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/TikTokApi/browser.py", line 116, in create_page
    context = self.browser.newContext(**iphone)
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/playwright/sync_api.py", line 6188, in newContext
    self._sync(
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/playwright/browser.py", line 114, in newContext
    channel = await self._channel.send("newContext", params)
  File "/home/wangxiaoyang/miniconda3/lib/python3.8/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Playwright.createContext): Browser has been closed.

**Comment by davidteather** [comment]
I can't seem to replicate here's my code. I've made changes to the API in the last 10 days so maybe that fixed it
```
from TikTokApi import TikTokApi

api = TikTokApi(custom_verifyFp="my_s_v_web_id")

print(api.byHashtag('funny', count=500))
```

**Comment by davidteather** [comment]
If you're still facing the same problem I recommend trying to follow [playwright's quickstart tutorial](https://github.com/microsoft/playwright-python#sync-api) it might give you a more detailed error that you can debug with their community.
