### ISSUE TITLE
[BUG] - Getting error expected string or bytes-like object

### ISSUE THREAD

**Issue by Juzteet** [davidteather/TikTok-Api#391]
**Describe the bug**

Getting "TypeError: expected string or bytes-like object" when executing api.byUsername

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
import random
api = TikTokApi()
did = random.randint(6800000000000000000, 6900000000000000000)
t = api.byUsername(username='thqttie', did=did, custom_verifyFp='verify_************************************uS5')[0]
```

Put the error trace below if there's any error thrown.

```
Traceback (most recent call last):
  File "C:\Users\Kris\Desktop\tiktok bot\main.py", line 6, in <module>
    t = api.byUsername(username='thqttie', did=did, custom_verifyFp='verify_********************************************')[0]
  File "C:\Users\Kris\Desktop\tiktok bot\TikTokApi\tiktok.py", line 488, in byUsername
    data = self.getUserObject(username, **kwargs)
  File "C:\Users\Kris\Desktop\tiktok bot\TikTokApi\tiktok.py", line 1062, in getUserObject
    return self.getUser(username, **kwargs)["userInfo"]["user"]
  File "C:\Users\Kris\Desktop\tiktok bot\TikTokApi\tiktok.py", line 1091, in getUser
    cookies=self.get_cookies(**kwargs),
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 316, in prepare
    self.prepare_cookies(cookies)
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 573, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "C:\Users\Kris\AppData\Roaming\Python\Python37\site-packages\requests\cookies.py", line 142, in get_cookie_header
    jar.add_cookie_header(r)
  File "C:\Users\Kris\AppData\Local\Programs\Thonny\lib\http\cookiejar.py", line 1364, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "C:\Users\Kris\AppData\Local\Programs\Thonny\lib\http\cookiejar.py", line 1323, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 3.8.1

**Comment by davidteather** [comment]
You might want to make your did a string 
```
did = str(random.randint(6800000000000000000, 6900000000000000000))
```

that'll probably fix it
