### ISSUE TITLE
[BUG] -ERROR:root:Tiktok response is empty

### ISSUE THREAD

**Issue by magicub** [davidteather/TikTok-Api#394]
I added the custom_verifyFP and i was able to get the info of videos by Username, however starting monday  I'm getting the message **ERROR:root:Tiktok response is empty**. Should I get a proxy, should i and the custom_verifyFP somewhere else on the code? 

**Here is the code**
```
from TikTokApi import TikTokApi
custom_verifyFP = 'verify_xxxxxxxxxxxxxx'
api = TikTokApi()

n_videos = 1000
username = 'crisbasabe'
user_videos = api.byUsername(username, count=n_videos)
import pandas as pd

def simple_dict(tiktok_dict):
  to_return = {}
  to_return['user_name'] = tiktok_dict['author']['uniqueId']
  to_return['user_id'] = tiktok_dict['author']['id']
  to_return['video_id'] = tiktok_dict['id']
  to_return['video_desc'] = tiktok_dict['desc']
  to_return['video_time'] = tiktok_dict['createTime']
  to_return['video_length'] = tiktok_dict['video']['duration']
  to_return['video_link'] = 'https://www.tiktok.com/@{}/video/{}?lang=en'.format(to_return['user_name'], to_return['video_id'])  
  to_return['n_likes'] = tiktok_dict['stats']['diggCount']
  to_return['n_shares'] = tiktok_dict['stats']['shareCount']
  to_return['n_comments'] = tiktok_dict['stats']['commentCount']
  to_return['n_plays'] = tiktok_dict['stats']['playCount']  
  return to_return


user_videos = [simple_dict(v) for v in user_videos]
user_videos_df = pd.DataFrame(user_videos)
user_videos_df.to_csv('{}_videos.csv'.format(username),index=False)
```

**Error Message**

```
#ERROR:root:Tiktok response is empty
Traceback (most recent call last):
  File "c:/Users/John Mario/hello/basabe01.py", line 8, in <module>
    user_videos = api.byUsername(username, count=n_videos)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 488, in byUsername
    data = self.getUserObject(username, **kwargs)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1062, in getUserObject
    return self.getUser(username, **kwargs)["userInfo"]["user"]
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1105, in getUser
    raise TikTokCaptchaError() from None
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters
```

 - OS:  Windows 10
 - TikTokApi Version e.g. 3.8.1

**Comment by robindz** [comment]
You aren't using `custom_verifyFp` anywhere? You just assigned a value to it, but aren't using it when you call `byUsername`. What happens if you use `user_videos = api.byUsername(username, count=n_videos, custom_verifyFp=custom_verifyFP)`?

**Comment by demon071** [comment]
If you want to get the video list, just use the request to api tiktok, https://tiktok.com/node/share/... but the video will have watermark

**Comment by magicub** [comment]
Wh

> 
> 
> If you want to get the video list, just use the request to api tiktok, https://tiktok.com/node/share/... but the video will have watermark

What i want is the stats: number of likes, plays, comments.  I´ve tried yesterday and it worked, but this morning failed, it's on and off.

**Comment by davidteather** [comment]
Changed a few things in the most recent update might help make sure to use custom_verifyFp
