### ISSUE TITLE
[BUG] Could not locate hashtag ID

### ISSUE THREAD

**Issue by theparcel** [davidteather/TikTok-Api#40]
**Describe the bug**
```

Traceback (most recent call last):
  File ".\getHashtag.py", line 10, in <module>
    result = api.search_by_hashtag("xmas")
  File "C:\Users\loren\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokApi\tiktok.py", line 124, in search_by_hashtag
    raise Exception("Could not locate hashtag ID: Tried " + str(tries) + " times")
Exception: Could not locate hashtag ID: Tried 10 times

```
**The buggy code**
```

from TikTokApi import TikTokapi

# Starts The Api Class
api = TikTokapi("browsermob-proxy/bin/browsermob-proxy")

# The Number of trending TikToks you want to be displayed
results = 10

# Searches for the top trending hashtag of TikTok
result = api.search_by_hashtag("xmas")

for tiktok in result:
    # Prints the text of the tiktok
    print(tiktok['itemInfos']['text'])

print(len(result))
api.quit_browser()
```

**Comment by davidteather** [comment]
Just uploaded V2.3.4 to pypi it fixes this issue.
