### ISSUE TITLE
[BUG] - Quick Start Guide doesn't work

### ISSUE THREAD

**Issue by leourl** [davidteather/TikTok-Api#418]
**Describe the bug**

Quick Start Guide doesn't work

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
# If playwright doesn't work for you try to use selenium
# api = TikTokApi.get_instance(use_selenium=True)

results = 10
custom_verifyFp = "[my cookie was here]"

# Since TikTok changed their API you need to use the custom_verifyFp option.
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.trending(use_test_endpoints=True, count=results, custom_verifyFp=custom_verifyFp)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))
```

**Error Trace (if any)**

```
# ERROR:root:Expecting value: line 1 column 1 (char 0)
ERROR:root:Converting response to JSON failed response is below (probably empty)
Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 163, in getData
    return r.json()
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    trending = api.trending(use_test_endpoints=True, count=results, custom_verifyFp=custom_verifyFp)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 256, in trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 170, in getData
    raise Exception("Invalid Response")
Exception: Invalid Response
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.7.9] - if out of date upgrade before posting an issue

**Additional context**

what am i doing wrong?

**Comment by davidteather** [comment]
Was just working on a release to fix this. Try the newest version of the package run `pip install TikTokApi --upgrade`

**Comment by leourl** [comment]
tks, i just saw that i forgot to make a title for this error, haha

i upgraded and now i get this error

```
ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"C-VbP14a*A09hUr4yebCO5yxQRYmy-6ZF70WZBL4398hOyAvrAXZG4XRKwxn2EW0DytCcL2i5qnHhqR*rWAnTZ2aikrpC5m4M*KkCKhrMixPKd6wLDeSpa8gDawjRqkOGV0JD7f-RazUtebLJQZ6JhJta7eIjjRDXG1DLbGtTER2aSj-zb8gk5knSYqWh7wP-Bbiy*kcDy8cgOhBvh470u8ePeq2ix8lVWnttTGPttgqQaDuDiglZMDT5o*rt5g4-X74njKF23eCTY*lx*PCPcQZrBSGY9wUgYXSobJz","verify_event":"","fp":"verify_kij9zchr_FaPLPEWz_Ru8u_4TNb_BQLC_fPP98KiEUuqL","scene":""}
ERROR:root:{'tt_webid': '3524848109801567299', 'tt_webid_v2': '3524848109801567299', 'tt_csrf_token': 'ePFXziCpkDphLJvw'}
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    trending = api.trending(count=results, custom_verifyFp=custom_verifyFp)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 336, in trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 202, in getData
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters
```

**Comment by Ghostigme** [comment]
+1 some error

**Comment by davidteather** [comment]
You can try
```
api = TikTokApi.get_instance(use_test_endpoints=True)
```

or provide a `verifyFp` parameter. Go to #390
