### ISSUE TITLE
byHashtag not work

### ISSUE THREAD

**Issue by yswtrue** [davidteather/TikTok-Api#425]

**Comment by ziyueluo** [comment]
I found the same issue. Any solutions?

**Comment by ziyueluo** [comment]
I got the following error:
ERROR:root:TikTok response: 
Traceback (most recent call last):
  File "D:/Work/Tool/tiktok/scrape_tt.py", line 65, in <module>
    hashtags=api.byHashtag(h,did=did,proxies=proxies,count=2000,custom_verifyFp=verifyfp)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 850, in byHashtag
    res = self.getData(url=api_url, **kwargs)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 213, in getData
    ) from None
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/challenge/item_list/?aid=1988&app_name=tiktok_web&device_platform...

**Comment by lekhanhtoan37** [comment]
I got the same error: TikTokApi.exceptions.EmptyResponseError

**Comment by davidteather** [comment]
Try the following `api = TikTokApi.get_instance(use_test_endpoints=True)` it should work for at least now
