### ISSUE TITLE
Unable to run the example from the command line

### ISSUE THREAD

**Issue by jaykeerti** [davidteather/TikTok-Api#430]
I am trying to run the example code and I am not able to get the desired output

```
from TikTokApi import TikTokApi
api = TikTokApi(use_test_endpoints=True)
count = 30

tiktoks = api.byUsername("americanredcross", count=count)

for tiktok in tiktoks:
    print(tiktok)
```
i am getting the following error

```
D:\TikTok>python trending.py
Traceback (most recent call last):
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x037CDC70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url: /@americanredcross?lang=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037CDC70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trending.py", line 23, in <module>
    tiktoks = api.byUsername("americanredcross", count=count)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 518, in byUsername
    data = self.getUserObject(username, **kwargs)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1087, in getUserObject
    return self.getUser(username, **kwargs)["userInfo"]["user"]
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1104, in getUser
    r = requests.get(
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url: /@americanredcross?lang=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x037CDC70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

 - OS:  Windows 10
 - TikTokApi Version 3.8.6 (Latest)

**Comment by davidteather** [comment]
Are you able to open [americanredcross's TikTok](https://www.tiktok.com/@americanredcross) it seems like your internet is refusing connection to TikTok

**Comment by jaykeerti** [comment]
@davidteather I think I might need to use a proxy then. can you suggest some?

**Comment by davidteather** [comment]
Luminati is pretty good. This library also might not support python REPL because of how playwright/selenium works
