### ISSUE TITLE
[BUG] - AttributeError: 'TikTokApi' object has no attribute 'width'

### ISSUE THREAD

**Issue by yswtrue** [davidteather/TikTok-Api#449]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here
api = TikTokApi.get_instance(
        custom_verifyFp=get_custom_verifyFp(language, proxy))
users = api.getSuggestedUsersbyIDCrawler(
            count=count, startingId=user_id, language=language, proxy=proxy)

```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 50, in run
    raise task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 706, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 35, in run
    return task._orig_run(*args, **kwargs)
  File "/app/seatower_analytics/tiktok/tasks.py", line 121, in tiktok_user_crawler
    users = api.getSuggestedUsersbyIDCrawler(
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 1203, in getSuggestedUsersbyIDCrawler
    newUsers = self.getSuggestedUsersbyID(userId=userId, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 1173, in getSuggestedUsersbyID
    BASE_URL, self.__add_new_params__(), urlencode(query)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 1552, in __add_new_params__
    "screen_width": self.width,
AttributeError: 'TikTokApi' object has no attribute 'width'

--



```

**Desktop (please complete the following information):**
 - OS: celeryworker in centos
 - TikTokApi Version 3.8.8

**Additional context**

**Comment by davidteather** [comment]
Probably an issue with launching playwright-python I recommend you look at their repo and see if their quickstart guide works. If not search their issues

**Comment by idilkylmz** [comment]
Hi @davidteather I get the same error even when I use get_instance(use_selenium=True) here is the code in jupyter notebook

api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_selenium=True)
tiktoks = api.trending()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-699d78a88a82> in <module>
----> 1 tiktoks = api.trending(count=results, custom_verifyFp=verifyFp)

~/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py in trending(self, count, minCursor, maxCursor, **kwargs)
    332             }
    333             api_url = "{}api/item_list/?{}&{}".format(
--> 334                 BASE_URL, self.__add_new_params__(), urlencode(query)
    335             )
    336             res = self.getData(url=api_url, **kwargs)

~/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py in __add_new_params__(self)
   1566             "user_agent": self.__format_new_params__(self.userAgent),
   1567             "cookie_enabled": "true",
-> 1568             "screen_width": self.width,
   1569             "screen_height": self.height,
   1570             "browser_language": self.browser_language,

AttributeError: 'TikTokApi' object has no attribute 'width'

**Comment by Giuliagiorgi** [comment]
Me too

**Comment by wenyiyan0920** [comment]
Me too
