### ISSUE TITLE
[BUG] - TikTokApi Class

### ISSUE THREAD

**Issue by TsyXa** [davidteather/TikTok-Api#450]
Hi there,
I'm currently making an attempt with my existing knowledge of python to try and create a script that can give me a list of four letter names, ending when it finds one which is available. I have however been experiencing an error with the very first step- the api definition. I've frantically searched google, even going to page 2 at one point (i know right!) trying to find a solution but I can't seem to find one.

```
from TikTokApi import TikTokApi
import random

api = TikTokApi()

print(api.trending(count=1))

for i in range(38**4):
    name = ""
    string = "qwertyuiopasdfghjklzxcvbnm1234567890._"
    for i2 in range(4):
        choice = random.randint(0, 37)
        name += string[choice]
    try:
        user = api.getUser(username=name)
        print(f"{name} not available")
    except:
        print(name)
        raise
```

I expected this script to grab a random string, try to find the user and if not found show the name and break. If not, it would continue to cycle round, showing the attempted username with a "Not available" message.

```
Traceback (most recent call last):
  File "C:/python/tiktokNameGen.py", line 6, in <module>
    api = TikTokApi()
  File "C:\python\lib\site-packages\TikTokApi\tiktok.py", line 56, in __init__
    self.browser = browser(**kwargs)
  File "C:\python\lib\site-packages\TikTokApi\browser.py", line 82, in __init__
    raise e
  File "C:\python\lib\site-packages\TikTokApi\browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "C:\python\lib\site-packages\TikTokApi\browser.py", line 26, in get_playwright
    raise e
  File "C:\python\lib\site-packages\TikTokApi\browser.py", line 24, in get_playwright
    playwright = sync_playwright().start()
  File "C:\python\lib\site-packages\playwright\_main.py", line 84, in start
    return self.__enter__()
  File "C:\python\lib\site-packages\playwright\_main.py", line 78, in __enter__
    dispatcher_fiber.switch()
  File "C:\python\lib\site-packages\playwright\_main.py", line 59, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "C:\python\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\python\lib\site-packages\playwright\_connection.py", line 134, in run_as_sync
    await self.run()
  File "C:\python\lib\site-packages\playwright\_connection.py", line 139, in run
    await self._transport.run()
  File "C:\python\lib\site-packages\playwright\_transport.py", line 45, in run
    limit=32768,
  File "C:\python\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\python\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "C:\python\lib\asyncio\windows_events.py", line 372, in _make_subprocess_transport
    **kwargs)
  File "C:\python\lib\asyncio\base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\python\lib\asyncio\windows_events.py", line 819, in _start
    bufsize=bufsize, **kwargs)
  File "C:\python\lib\asyncio\windows_utils.py", line 155, in __init__
    stderr=stderr_wfd, **kwds)
  File "C:\python\lib\subprocess.py", line 753, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\python\lib\subprocess.py", line 1106, in _get_handles
    errwrite = msvcrt.get_osfhandle(stderr.fileno())
io.UnsupportedOperation: fileno
```

 - OS: Windows 10
 - TikTokApi Version 3.8.8

**Comment by davidteather** [comment]
Hmm seems like your playwright instance might not be launching properly, you also might want to try `api = TikTokApi.get_instance(use_test_endpoints=True)` as it's better formatting for this package. The test endpoints may stop working at some point in the future but it's easier to use.

You may want to look at the [playwright-python issues](https://github.com/microsoft/playwright-python/issues?q=io.UnsupportedOperation%3A+fileno) they might be able to help you there. Are you by chance using python REPL, the terminal rather than running `python file.py`? that's the only thing I could see making that error based on playwright python issues
