### ISSUE TITLE
Key Error : challengeInfo

### ISSUE THREAD

**Issue by ziyueluo** [davidteather/TikTok-Api#492]
Hi, I met a new problem when using byHashtag method: 

Traceback (most recent call last):
    hashtags=api.byHashtag(h,did=did,custom_verifyFp=verifyfp,count=2000,proxy=proxy)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 836, in byHashtag
    id = self.getHashtagObject(hashtag)["challengeInfo"]["challenge"]["id"]
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 893, in getHashtagObject
    if data["challengeInfo"].get("challenge") is None:
KeyError: 'challengeInfo'

The code used to be working. Do you have any idea why I'm having this error ?

**Comment by davidteather** [comment]
Hmm, not sure about this one can you show the code you're providing? I'd recommend following [this video](https://www.youtube.com/watch?v=zwLmLfVI-VQ)
