### ISSUE TITLE
getHashtagObject, byHashtag not working

### ISSUE THREAD

**Issue by natnaelab** [davidteather/TikTok-Api#494]
```
from TikTokApi import TikTokApi

api = TikTokApi.get_instance(use_selenium=True, use_api_endpoints=True)

ttvideos = api.byHashtag('hashtag', count=10)

for video in ttvideos:
    print(video)

print(len(ttvideos))
```

i have tried `api = TikTokApi(custom_verifyFp='token')` still not working...

Error log
```
ERROR:root:TikTok response: {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/home/user/Documents/workspace/projects/tty/env/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 196, in getData
    json = r.json()
  File "/home/user/Documents/workspace/projects/tty/env/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Documents/workspace/projects/tty/main.py", line 8, in <module>
    ttvideos = api.byHashtag('habeshatiktok', count=10)
  File "/home/user/Documents/workspace/projects/tty/env/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 836, in byHashtag
    id = self.getHashtagObject(hashtag)["challengeInfo"]["challenge"]["id"]
  File "/home/user/Documents/workspace/projects/tty/env/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 892, in getHashtagObject
    data = self.getData(url=api_url, **kwargs)
  File "/home/user/Documents/workspace/projects/tty/env/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 217, in getData
    raise JSONDecodeFailure() from e
TikTokApi.exceptions.JSONDecodeFailure: TikTok sent invalid JSON back
```

**Comment by davidteather** [comment]
Selenium is bugged and probably being detected

**Comment by natnaelab** [comment]
unfortunately playwright is not working on my machine (Manjaro 5.10) either.

```
playwright._types.Error: Host system is missing dependencies!

  Missing libraries are:
      libicui18n.so.66
      libicuuc.so.66
      libwebp.so.6
      libenchant.so.1
```

**Comment by tmahmood** [comment]
Having the same issue. Both with playwright and Selenium

**Comment by davidteather** [comment]
Related to #434
