### ISSUE TITLE
Installing pip install command on mac

### ISSUE THREAD

**Issue by soultrain06** [davidteather/TikTok-Api#498]
When installing the pip its giving me a weird code

 ~ % pip install TikTokAPI       
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

pip install TikTokAPI

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
You're trying to install it onto python 2.7 try `pip3 install TikTokApi`
