### ISSUE TITLE
[BUG] - Is the project working on ubuntu?

### ISSUE THREAD

**Issue by MarcoLavoro** [davidteather/TikTok-Api#500]
**Describe the bug**

the program stops and give me an error, just followed this instruction:

`pip install TikTokApi
python -m playwright install`

and then used this:

**The buggy code**

      from TikTokApi import TikTokApi
      api = TikTokApi.get_instance()
      # If playwright doesn't work for you try to use selenium
      # api = TikTokApi.get_instance(use_selenium=True)
      
      results = 10
      
      # Since TikTok changed their API you need to use the custom_verifyFp option.
      # In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
      trending = api.trending(count=results, custom_verifyFp="verify_mycode")
      
      for tiktok in trending:
          # Prints the id of the tiktok
          print(tiktok['id'])
      
      print(len(trending))

**Expected behavior**

works properly

**Error Trace (if any)**

    python3 '/home/ma/Scrivania/tiktok/TicTokTest.py'
    Traceback (most recent call last):
    File "/home/ma/Scrivania/tiktok/TicTokTest.py", line 2, in
    api = TikTokApi.get_instance()
    File "/home/ma/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 89, in get_instance
    TikTokApi(**kwargs)
    File "/home/ma/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 56, in init
    self.browser = browser(**kwargs)
    File "/home/ma/.local/lib/python3.8/site-packages/TikTokApi/browser.py", line 82, in init
    raise e
    File "/home/ma/.local/lib/python3.8/site-packages/TikTokApi/browser.py", line 78, in init
    self.browser = get_playwright().webkit.launch(
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/sync_api.py", line 6974, in launch
    self._sync(
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/_sync_base.py", line 97, in _sync
    return future.result()
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/_browser_type.py", line 78, in launch
    raise e
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/_browser_type.py", line 74, in launch
    return from_channel(await self._channel.send("launch", params))
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
    File "/home/ma/.local/lib/python3.8/site-packages/playwright/_connection.py", line 47, in inner_send
    result = await callback.future
    playwright._types.Error: Host system is missing dependencies!
    
    Missing libraries are:
    libicui18n.so.66
    libicuuc.so.66
    libgstcodecparsers-1.0.so.0
    libenchant.so.1
    
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

**Comment by jaoxford** [comment]
You'll need to install those dependencies.

**Comment by davidteather** [comment]
Yeah, project works on ubuntu tests pass on ubuntu, you need the libraries from the comment above.

**Comment by MarcoLavoro** [comment]
> libicui18n

thanks a lot, since I am a noob on ubuntu can I ask you how to do that please?

**Comment by MarcoLavoro** [comment]
> You'll need to install those dependencies.
> 
> > ```
> > Missing libraries are:
> > libicui18n.so.66
> > libicuuc.so.66
> > libgstcodecparsers-1.0.so.0
> > libenchant.so.1
> > 
> > Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
> > ```

thanks a lot, since I am a noob on ubuntu can I ask you how to do that please?

**Comment by MarcoLavoro** [comment]
i tried with sudo apt install libicui18n.so.66 but it tell me that it not finded it

**Comment by dbobrenko** [comment]
Solution (Ubuntu 20.04):
```
# Install missing libenchant:
sudo apt install -y libenchant1c2a

# Add libicu66 repository:
echo "deb [arch=amd64] http://cz.archive.ubuntu.com/ubuntu focal main" | sudo tee -a /etc/apt/sources.list

# Install missing libicu66:
sudo apt install -y libicu66
```

**Comment by samkohli** [comment]
E: Unable to locate package libenchant1c2a
