### ISSUE TITLE
[INSTALLATION] - "webkit" browser was not found while using docker

### ISSUE THREAD

**Issue by kami4ka** [davidteather/TikTok-Api#502]
**Describe the error**

I've copied docker file content into my dockerfile + added FFMPEG, but getting the following error while trying to run the code

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/playwright/_browser_type.py", line 74, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._types.Error: Failed to launch webkit because executable doesn't exist at /root/.cache/ms-playwright/webkit-1402/pw_run.sh
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 118, in <module>
    api = TikTokApi.get_instance(custom_verifyFp=verifyFp)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 89, in get_instance
    TikTokApi(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 56, in __init__
    self.browser = browser(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api.py", line 6974, in launch
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_sync_base.py", line 97, in _sync
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_browser_type.py", line 77, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

make: *** [run] Error 1

```

**The buggy code**

My dockerfile content:

```
FROM mcr.microsoft.com/playwright:focal

RUN apt-get update && apt-get install -y python3-pip ffmpeg
RUN pip3 install TikTokApi
WORKDIR /app
```

How I'm running it:

```
run:
	docker build -t tiktok-bot .
	docker run --rm -it -v $(shell pwd):/app tiktok-bot python3 main.py
```

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS latest]
 - TikTokApi Version [e.g. 3.9.0] - from the dockerfile
 
 PS: it worked previously, probably, a month ago

**Comment by kami4ka** [comment]
Hi, @davidteather . Should v1.9.1 fix this issue?

**Comment by lionneclement** [comment]
@kami4ka I add `RUN python -m playwright install` and it's working

**Comment by kami4ka** [comment]
It's work for me now
