### ISSUE TITLE
[BUG] - gevent.exceptions.InvalidSwitchError: Invalid switch into Event.wait(): ()

### ISSUE THREAD

**Issue by K1NDER-ai** [davidteather/TikTok-Api#544]
Sorry, I'm from Russia, I use a translator. Your library is working properly, but often after a while such an error is thrown out

Traceback (most recent call last):
  File "main.py", line 1283, in <module>
    _token_bot.polling(none_stop=True, interval=0)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 487, in polling
    self.__non_threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 591, in __non_threaded_polling
    raise e
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 562, in __non_threaded_polling
    self.__retrieve_updates(timeout, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 322, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout, long_polling_timeout = long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 292, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 281, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 126, in _make_request
    result = _get_req_session().request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 325, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 146, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 107, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 105, in do_poll
    return poll_obj.poll(t)
  File "/usr/local/lib/python3.8/dist-packages/gevent/select.py", line 314, in poll
    result.event.wait(timeout=timeout)
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_context_manager.py", line 48, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.8/dist-packages/gevent/selectors.py", line 201, in select
    self._ready.wait(timeout)
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 455, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
gevent.exceptions.InvalidSwitchError: Invalid switch into Event.wait(): ()

If I knew that there could be a problem at all, then I would take the code in try except, here is a possible problem area

`def loadPreset(message):
    while True:
        mycursor = mydb.cursor()
        mycursor.execute(f"SELECT * FROM users WHERE id='{message.from_user.id}'")

        myresult_user = mycursor.fetchone()
        mycursor.close()
        if myresult_user[7] == 0:
            _token_bot.send_message(message.chat.id, "⚠Настрой пресеты!.")
            break

        if myresult_user[8] == 0:
            break

        try:
            trending = api.trending(50)
        except ValueError:
            return _token_bot.send_message(message.chat.id, "⚠Отправлены неверные данные. Попробуйте еще раз.")

        i = 0
        for tiktok in trending:
            if i >= 3:
                break
            stop_donwload = 0
            mycursor = mydb.cursor()
            mycursor.execute(f"SELECT * FROM tokens WHERE user_id='{message.from_user.id}'")

            myresult = mycursor.fetchall()
            mycursor.close()
            for down_down in myresult:
                mycursor1 = mydb.cursor()
                mycursor1.execute(f"SELECT * FROM clips WHERE token='{down_down[2]}'")

                myresult = mycursor1.fetchall()
                mycursor1.close()
                for row in myresult:
                    if row[2] == tiktok["id"]:
                        stop_donwload = 1
                        break

            if i >= 3:
                break
            if stop_donwload == 0:
                url = "https://www.tiktok.com/@" + tiktok["author"]["uniqueId"] + "/video/" + tiktok["id"]

                x = threading.Thread(target=_load_snaptik, args=(url, message, tiktok["desc"], 1, tiktok["id"]))
                x.start()
                i = i + 1

        time.sleep(myresult_user[7])`

**Comment by davidteather** [comment]
Probably #576
