### ISSUE TITLE
[BUG] - How to avoid empty response from TikTok

### ISSUE THREAD

**Issue by omkar2810** [davidteather/TikTok-Api#555]
**Describe the bug**

I am trying to collect the posts for a large number of users, and after a while the API starts getting empty responses from TikTok. I have tried changing custom_verifyFp, custom_did and use_test_endpoints = True. Despite all this, I am getting the same error.

Is there a way to prevent this, by varying some other values or changing the user agent of the request.

**Comment by davidteather** [comment]
You’ll have to use different proxies as you’re probably getting IP throttled

**Comment by omkar2810** [comment]
@davidteather would having time.sleep() statements in between the queries help? Since it seems like there is a rate limit imposed by TikTok.

**Comment by davidteather** [comment]
> would having time.sleep() statements help?

Yes most likely. There's also a built-in `request_delay` parameter to the constructor of the package. You can more about it in the docs

**Comment by Antonytm** [comment]
I get the same for the first request.

**Comment by Antonytm** [comment]
```
ERROR:root:TikTok response:
Traceback (most recent call last):
  File "trending.py", line 8, in <module>
    trending = api.trending(results)
  File "C:\Python37\lib\site-packages\TikTokApi\tiktok.py", line 404, in by_trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Python37\lib\site-packages\TikTokApi\tiktok.py", line 283, in get_data
    ) from None
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/recommend/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=640&screen_height=668&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=5&id=1&secUid=&sourceType=12&appId=1233&itemID=1&insertedItemID=&region=US&priority_region=US&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&did=8220682057072991758&_signature=_02B4Z6wo00f01bbHEPwAAIBAramBkKbyBvW21hRAAA3Jab
```
