### ISSUE TITLE
[BUG] - greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by MasterKeyy** [davidteather/TikTok-Api#556]
**Describe the bug**

I can't run TikTokApi from 2 different thread

**The buggy code**
```python
class TestTiktok(threading.Thread):
    def run(self):
        api = TikTokApi.get_instance()
        posts = api.userPosts(
            "6745191554350760966",
            "MS4wLjABAAAAM3R2BtjzVT-uAtstkl2iugMzC6AtnpkojJbjiOdDDrdsTiTR75-8lyWJCY5VvDrZ",
            30,
        )
        for post in posts:
            print(post["desc"])

tiktok1 = TestTiktok()
tiktok1.start()
tiktok1.join()

tiktok2 = TestTiktok()
tiktok2.start()
tiktok2.join()
```

**Expected behavior**

Only the first thread is working, I have the error below for the second thead. 
I would expect that TikTokApi is working in different thread.

**Error Trace**
```
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\***\run.py", line 18, in run
    posts = api.userPosts(
  File "C:\Users\***\TikTokApi\tiktok.py", line 558, in user_posts
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\***\TikTokApi\tiktok.py", line 228, in get_data
    verify_fp, did, signature = self.browser.sign_url(**kwargs)
  File "C:\Users\***\TikTokApi\browser.py", line 164, in sign_url
    context = self.create_context()
  File "C:\Users\***\TikTokApi\browser.py", line 117, in create_context
    context = self.browser.new_context(**iphone)
  File "C:\Users\***\lib\site-packages\playwright\sync_api\_generated.py", line 8611, in new_context
    self._sync(
  File "C:\Users\***\lib\site-packages\playwright\_impl\_sync_base.py", line 101, in _sync
    self._dispatcher_fiber.switch()
greenlet.error: cannot switch to a different thread
```

**Desktop:**
 - OS: Windows 10
 - TikTokApi Version 3.9.5

**Comment by marcelogrsp** [comment]
same problem! @davidteather check it for us urgently please :)

**Comment by mathiskaddouri** [comment]
Putting these 2 following lines on top of your code can resolve the problem.
```python
from gevent import monkey
monkey.patch_all()
```


Or another solution I have experimented, is to launch Tiktok from an new process instead of a new thread.

**Comment by Auth0rM0rgan** [comment]
Hey @MasterKeyy, @davidteather, `monkey.patch_all()` is not working and Im getting the same error even by using the monkey. any solution? Thanks!

**Comment by MasterKeyy** [comment]
@Auth0rM0rgan  Try to use Process instead of Thread, it worked in my case
