### ISSUE TITLE
[BUG] - dowloadTikTok.py example 

### ISSUE THREAD

**Issue by mathiskaddouri** [davidteather/TikTok-Api#559]
**Describe the bug**

The example to download a video in `examples/downloadTikTok.py` doesn't work.

**Error Trace**
```
ERROR:root:TikTok response:
Traceback (most recent call last):
  File "C:\Users\***\TikTok-Api\examples\downloadTikTok.py", line 13, in <module>
    trending = api.trending(custom_did=did)
  File "C:\Users\***\venv\lib\site-packages\tiktokapi-3.9.5-py3.9.egg\TikTokApi\tiktok.py", line 404, in by_trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\***\venv\lib\site-packages\tiktokapi-3.9.5-py3.9.egg\TikTokApi\tiktok.py", line 281, in get_data
    raise EmptyResponseError(
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/recommend/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=588&screen_height=1604&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=30&id=1&secUid=&sourceType=12&appId=1233&itemID=1&insertedItemID=&region=US&priority_region=US&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&did=705430474&_signature=_02B4Z6wo00f01MPvxewAAIBB2IFUgcVt5JjD.sFAAFCUf8
```

**Desktop:**
 - OS: Windows 10
 - TikTokApi Version 3.9.5 (latest from git clone & python setup.py install)

**Comment by alzeric** [comment]
Give this a try

`api = TikTokApi.get_instance(use_test_endpoints=True)`

**Comment by davidteather** [comment]
The example is slightly outdated it's likely the did parameter is being generated wrong in that. Please view the YouTube video linked in the readme on how to download a video.
