### ISSUE TITLE
[BUG] - Error when running the example

### ISSUE THREAD

**Issue by marcelogrsp** [davidteather/TikTok-Api#569]
**Describe the bug**
When running the example `python -m examples.getTrending`

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

# If playwright doesn't work for you try to use selenium
# api = TikTokApi.get_instance(use_selenium=True)

results = 10

# Since TikTok changed their API you need to use the custom_verifyFp option. 
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.trending(count=results, custom_verifyFp="")

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))
```

**Expected behavior**
Expected to return:
```
6928073780141018373
6951095255026502918
6931147355534281990
6925232616706772229
6952494753665551621
6924082241651920133
6927179705627987201
6934764292193520902
6952877511910968582
6940681019091700997
10
```

When debbuging, the errors occurs at line 77 of `TikTokApi/browser.py`

```
...
        try:
            self.browser = get_playwright().webkit.launch(
                args=self.args, **self.options
            )
        except Exception as e:
            raise e
            logging.critical(e)
...
```
**Error Trace (if any)**
```
Traceback (most recent call last):
  File "/root/Web-Scrapping-Bot/api/tkapi_test.py", line 2, in <module>
    api = TikTokApi.get_instance()
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 148, in get_instance
    TikTokApi(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 58, in __init__
    self.browser = browser(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 8941, in launch
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_type.py", line 79, in launch
    raise e
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_type.py", line 75, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Protocol error (Playwright.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/webkit-1446/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=55666
[pid=55666][err] /root/.cache/ms-playwright/webkit-1446/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libharfbuzz-icu.so.0: cannot open shared object file: No such file or directory
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/webkit-1446/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=55666
[pid=55666][err] /root/.cache/ms-playwright/webkit-1446/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libharfbuzz-icu.so.0: cannot open shared object file: No such file or directory
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Desktop (please complete the following information):**
 - OS:
 ```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

 - TikTokApi Version [3.9.5]

**Comment by wasymshykh** [comment]
I had same issue yesterday on my Ubuntu 20.04 machine. After tireless searching and installing countless libraries it didn't work. 
I end up pulling playwright:bionic docker image, created container, bash into the container, pip installed tiktok-api and everything worked well.
