### ISSUE TITLE
[BUG] - playwright._impl._api_types.Error: Protocol error (Playwright.enable): Browser closed. on ubuntu server

### ISSUE THREAD

**Issue by jlchen2000** [davidteather/TikTok-Api#585]
It runs fine on my computer, but it doesn't run on my ubuntu server. I installed the package, and then I did the command
"python3 -m install playwright", and it installed everything but I still get the error on my ubuntu server. Any ideas on how to fix this? Here is the error that I get

 - ubuntu: 20.04.2
 - TikTokApi Version 3.9.5
 - Everything installed was on 5/10/2021
 Traceback (most recent call last):
  File "tvs_ubuntu.py", line 118, in <module>
    tiktok_vid, video_id = AutomatedTVS()
  File "tvs_ubuntu.py", line 10, in AutomatedTVS
    api = TikTokApi.get_instance(custom_verifyFp="keeping it a secret")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", li                                                                                                                                                             ne 148, in get_instance
    TikTokApi(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", li                                                                                                                                                             ne 58, in __init__
    self.browser = browser(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TikTokApi/browser.py", l                                                                                                                                                             ine 82, in __init__
    raise e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TikTokApi/browser.py", l                                                                                                                                                             ine 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/sync_api/_gen                                                                                                                                                             erated.py", line 8941, in launch
    self._sync(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/_impl/_sync_b                                                                                                                                                             ase.py", line 103, in _sync
    return task.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/_impl/_browse                                                                                                                                                             r_type.py", line 79, in launch
    raise e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/_impl/_browse                                                                                                                                                             r_type.py", line 75, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/_impl/_connec                                                                                                                                                             tion.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/playwright/_impl/_connec                                                                                                                                                             tion.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Protocol error (Playwright.enable): Browser c                                                                                                                                                             losed.
==================== Browser output: ====================
<launching> /home/ubuntu/.cache/ms-playwright/webkit-1446/pw_run.sh --inspector-                                                                                                                                                             pipe --headless --no-startup-window
<launched> pid=22644
[pid=22644][err] /home/ubuntu/.cache/ms-playwright/webkit-1446/minibrowser-wpe/b                                                                                                                                                             in/MiniBrowser: error while loading shared libraries: libatk-1.0.so.0: cannot op                                                                                                                                                             en shared object file: No such file or directory
=========================== logs ===========================
<launching> /home/ubuntu/.cache/ms-playwright/webkit-1446/pw_run.sh --inspector-                                                                                                                                                             pipe --headless --no-startup-window
<launched> pid=22644
[pid=22644][err] /home/ubuntu/.cache/ms-playwright/webkit-1446/minibrowser-wpe/b                                                                                                                                                             in/MiniBrowser: error while loading shared libraries: libatk-1.0.so.0: cannot op                                                                                                                                                             en shared object file: No such file or directory
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.

**Comment by radonys** [comment]
I am facing the same issue. 

Used Selenium with proxy on the Ubuntu Server to get it working. But only some functions are working.

**Comment by radonys** [comment]
I was able to run the API on Ubuntu Server (18.04 LTS) with MS Playwright. Just run this command: `playwright install-deps`.

Source: https://playwright.dev/python/docs/cli#install-system-dependencies

**Comment by nardo-leo** [comment]
Have the same issue inside Docker container:
_playwright._impl._api_types.Error: Navigation failed because page crashed!_

With additional logs:
_setting frame content, waiting until "load"_

**Comment by jlchen2000** [comment]
> I was able to run the API on Ubuntu Server (18.04 LTS) with MS Playwright. Just run this command: `playwright install-deps`.
> 
> Source: https://playwright.dev/python/docs/cli#install-system-dependencies

Yup worked for me
