### ISSUE TITLE
This event loop is already running

### ISSUE THREAD

**Issue by Ronghefeng** [davidteather/TikTok-Api#599]
When i execute this code "from TikTokApi import TikTokApi  api = TikTokApi.get_instance()" in django shell,an error ocuured:
Traceback (most recent call last):
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 99, in handle
    return getattr(self, shell)(options)
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 36, in ipython
    start_ipython(argv=[])
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/Users/rhf/workspace/seatower_analytics/.venv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 887, in run
    return loop.run_until_complete(
  File "/Users/rhf/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/Users/rhf/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

How can i resolve it?

**Comment by davidteather** [comment]
#576  #200
