### ISSUE TITLE
[BUG] - Please use the Async API instead.

### ISSUE THREAD

**Issue by Scarlet06** [davidteather/TikTok-Api#609]
**The bug**

I don't know if it is actually a bug, but I donk know how to solve this behavior:
I'm trying to call a function that uses TikTok-Api from an async function. Before the last update it worked just fine, but now it just sends me this error:

```
Ignoring exception in command add:
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\danie\Documents\Python\HrokiTikTok\HrokiDiscord.py", line 38, in add
    listofVideo= GM(num)
  File "C:\Users\danie\Documents\Python\HrokiTikTok\tiktok.py", line 9, in getMessage
    api = TikTokApi.get_instance()
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\tiktok.py", line 149, in get_instance
    TikTokApi(**kwargs)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\tiktok.py", line 59, in __init__
    self.browser = browser(**kwargs)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 82, in __init__
    raise e
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 26, in get_playwright
    raise e
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 24, in get_playwright
    playwright = sync_playwright().start()
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\sync_api\_context_manager.py", line 75, in start
    return self.__enter__()
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\sync_api\_context_manager.py", line 44, in __enter__
    Please use the Async API instead."""
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**My code**

As I previously said, I call a the function "GetMessage" from an async function. That's my tiktok code (Note that the error is thrown in `api = TikTokApi.get_instance()`):
```
from TikTokApi import TikTokApi
from datetime import datetime as dt

global username,api
username = 'hg_hroki'

def getMessage(n_videos):
    api = TikTokApi.get_instance()
    try:
        user = api.by_username(username=username,count=n_videos, custom_verifyFp="")
    except:
        try:
            veryfy="verify_kpgkv8zk_OFFOIMQ3_zshu_4LNk_BkIf_4Z0DV9AHwRK4"
            user = api.by_username(username=username,count=n_videos, custom_verifyFp=veryfy)
        except:
            veryfy=input("In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.\nPut it here: ")
            user = api.by_username(username=username,count=n_videos, custom_verifyFp=veryfy)

    to_return=[]
    user.reverse()
    for tiktok in user:

        el={}
        el['video_id'] = tiktok['id']
        el['video_desc'] = tiktok['desc']
        el['video_link'] = 'https://www.tiktok.com/@{}/video/{}?lang=en'\
            .format(tiktok['author']['uniqueId'],tiktok['id'])
        el['video_time'] = dt.fromtimestamp(tiktok['createTime'])\
                    .strftime('Caricato il %d-%m-%Y alle %H:%M')
        el['originCover'] = tiktok['video']['originCover']
        to_return.append(el)
    return to_return
```

And that's the async function (It's taken from my discord bot). I write in here only the calling part:
```
@bot.command()
async def add(ctx, *length: str):
    listofVideo= GM(2)
    ...
```

**Desktop:**
 - OS: Windows 10
 - TikTokApi Version 3.9.8

So... Is there a way to solve this problem? I've noticed in #591 that it may not be a problem TikTok-Api can solve... But I'm not sure the issue is the same

**Comment by isaackogan** [comment]
Not a bug, rather the intended use of the library. David's stated previously that he does not have any problem with this working in Async, but that it's a matter of manpower and knowledge to convert the library to support async _as well as_ sync usage.

**Comment by Scarlet06** [comment]
I've to say I'm self learning programming things and I know I have lots of "gaps" in this regards. But I've managed to make it work before the last update and now I'm missing something.
Anyway if this is not a bag I would close this "issue report", but if this doesn't create too much discomfort and/or confusion, can you give me at least some minor and vague advice please?

**Comment by Scarlet06** [comment]
I'll write it here as memento to a future me and to anyone who'll face the same problem: you can use https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

**Comment by ldantas05** [comment]
@Scarlet06 did you end up fixing the issue, I tried to edit the source code but no luck

**Comment by Scarlet06** [comment]
> @Scarlet06 did you end up fixing the issue, I tried to edit the source code but no luck

Hi! Yes I've managed to solve the issue with the procedure shown in the link. I've impoted also asyncio, and when I call the async function that uses tiktokapi I've created a loop  `loop = asyncio.get_running_loop()` and used `result = await loop.run_in_executor(<namefunction>)`

That's how I solved the issue. But later I've to fully understand how does asyncio work

**Comment by LocalsGitHub** [comment]
> > @Scarlet06 did you end up fixing the issue, I tried to edit the source code but no luck
> 
> Hi! Yes I've managed to solve the issue with the procedure shown in the link. I've impoted also asyncio, and when I call the async function that uses tiktokapi I've created a loop `loop = asyncio.get_running_loop()` and used `result = await loop.run_in_executor(<namefunction>)`
> 
> That's how I solved the issue. But later I've to fully understand how does asyncio work

Could you provide a more in-depth answer? What specific part of which script do you change. Did you add that code into the source code, or in the script itself that your trying to make? Could you provide examples?

**Comment by graingert** [comment]
I think this was fixed in https://github.com/davidteather/TikTok-Api/commit/34c309d82551c430b44030d4dead43e82e6d8cd5
