### ISSUE TITLE
[BUG] TikTokApi error to find region

### ISSUE THREAD

**Issue by dwissaaj** [davidteather/TikTok-Api#718]
**Des**

When I try use by_username it raise an error of region even that method didnt need region or return region

```
from TikTokApi import TikTokApi

api = TikTokApi.get_instance()

count = 30

tiktoks = api.by_username("jne", count=count)

for tiktok in tiktoks:
    print(tiktok)
```

**Expected behavior**

Print or return value of data

**Error**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-56e4c77815aa>", line 1, in <module>
    runfile('/home/levi/Downloads/Compressed/tiktok_testing-master/main.py', wdir='/home/levi/Downloads/Compressed/tiktok_testing-master')
  File "/snap/pycharm-professional/256/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/256/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/levi/Downloads/Compressed/tiktok_testing-master/main.py", line 7, in <module>
    tiktoks = api.by_username("jne", count=count)
  File "/home/levi/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 631, in by_username
    return self.user_posts(
  File "/home/levi/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 592, in user_posts
    BASE_URL, self.__add_url_params__(), urlencode(query)
  File "/home/levi/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 1703, in __add_url_params__
    "region": self.region or "US",
AttributeError: 'TikTokApi' object has no attribute 'region'
```

**OS**
Ubuntu 20.04.3 LTS

**Comment by fracogno** [comment]
I've found a solution [here](https://www.influencerhunters.com/apis/tt/user/posts?token=GQ96yJKZn3hWpQVz&depth=2&username=fedez)

**Comment by mina9999** [comment]
check https://github.com/davidteather/TikTok-Api/issues/672#issuecomment-917422706 @dwissaaj

**Comment by dwissaaj** [comment]
> check [#672 (comment)](https://github.com/davidteather/TikTok-Api/issues/672#issuecomment-917422706) @dwissaaj

Hi already try it before but not solve my problem.any suggestion?

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
