### ISSUE TITLE
[INSTALLATION] - playwright._impl._api_types.Error: Target closed

### ISSUE THREAD

**Issue by ManuMassi** [davidteather/TikTok-Api#746]
I just cloned the repo and I'm trying to run any example but whenever I try to run it gives me this error:

```
Traceback (most recent call last):
  File "/Users/manu/GitHub/TikTok-Api/examples/get_a_users_videos.py", line 4, in <module>
    api = TikTokApi.get_instance()
  File "/Users/manu/GitHub/TikTok-Api/TikTokApi/tiktok.py", line 155, in get_instance
    TikTokApi(**kwargs)
  File "/Users/manu/GitHub/TikTok-Api/TikTokApi/tiktok.py", line 65, in __init__
    self.browser = browser(**kwargs)
  File "/Users/manu/GitHub/TikTok-Api/TikTokApi/browser_utilities/browser.py", line 87, in __init__
    page = context.new_page()
  File "/Users/manu/GitHub/TikTok-Api/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9840, in new_page
    self._sync("browser_context.new_page", self._impl_obj.new_page())
  File "/Users/manu/GitHub/TikTok-Api/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/Users/manu/GitHub/TikTok-Api/venv/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 199, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/Users/manu/GitHub/TikTok-Api/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/manu/GitHub/TikTok-Api/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed

Process finished with exit code 1
```

I'm running the project on PyCharm in a virtual env. I have a MacBook Air M1 with macOS Monterey.

I tried to run the project out of PyCharm and it gives me this error:

```
CRITICAL:root:It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
/var/folders/8y/wp5ktd2d195gpgy8xq__r1_w0000gn/T/ipykernel_10419/599422689.py in <module>
      2 
      3 # Starts TikTokApi
----> 4 api = TikTokApi.get_instance()
      5 
      6 # The Number of trending TikToks you want to be displayed

~/GitHub/TikTok-Api/TikTokApi/tiktok.py in get_instance(**kwargs)
    153         """
    154         if not TikTokApi.__instance:
--> 155             TikTokApi(**kwargs)
    156         return TikTokApi.__instance
    157 

~/GitHub/TikTok-Api/TikTokApi/tiktok.py in __init__(self, **kwargs)
     63 
     64         if self.signer_url is None:
---> 65             self.browser = browser(**kwargs)
     66             self.userAgent = self.browser.userAgent
     67 

~/GitHub/TikTok-Api/TikTokApi/browser_utilities/browser.py in __init__(self, **kwargs)
     82         except Exception as e:
     83             logging.critical(e)
---> 84             raise e
     85 
     86         context = self.create_context(set_useragent=True)

~/GitHub/TikTok-Api/TikTokApi/browser_utilities/browser.py in __init__(self, **kwargs)
     77 
     78         try:
---> 79             self.browser = get_playwright().webkit.launch(
     80                 args=self.args, **self.options
     81             )

~/GitHub/TikTok-Api/TikTokApi/browser_utilities/browser.py in get_playwright()
     25             playwright = sync_playwright().start()
     26         except Exception as e:
---> 27             raise e
     28 
     29     return playwright

~/GitHub/TikTok-Api/TikTokApi/browser_utilities/browser.py in get_playwright()
     23     if playwright is None:
     24         try:
---> 25             playwright = sync_playwright().start()
     26         except Exception as e:
     27             raise e

~/miniforge3/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py in start(self)
     74 
     75     def start(self) -> SyncPlaywright:
---> 76         return self.__enter__()
     77 
     78     def __exit__(self, *args: Any) -> None:

~/miniforge3/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py in __enter__(self)
     40             own_loop = loop
     41         if loop.is_running():
---> 42             raise Error(
     43                 """It looks like you are using Playwright Sync API inside the asyncio loop.
     44 Please use the Async API instead."""


Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by osmanfatih** [comment]
The second error that you have shared I believe happened because you tried to run it on a notebook. For the first one, I am getting the same error and would appreciate any help.

**Comment by yushengnan0525** [comment]
I'm also getting the same error for the first one. Can someone please help us on it?

**Comment by anshuman852** [comment]
I am also getting the first error on a macbook air m1 running monterey

**Comment by davidteather** [comment]
#576
