### ISSUE TITLE
[ERROR] - ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by xarosh** [davidteather/TikTok-Api#755]
Traceback (most recent call last):
  File "E:\TikTokBot-master\tiktokbot.py", line 156, in <module>
    vidLength = getLength('downloaded/' + str(x) + ".mp4")
  File "E:\TikTokBot-master\tiktokbot.py", line 23, in getLength
    secs = float(secsval)
ValueError: could not convert string to float: ''

**Comment by davidteather** [comment]
Might be fixed with a new TikTokApi V4.1.0 release, but if not it's definitely an issue with the code on [TikTokBot](https://github.com/davidteather/TikTokBot)
