### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by yoooby** [davidteather/TikTok-Api#791]
**Describe the error**

Put the error trace here.

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
results = 10

# Since TikTok changed their API you need to use the custom_verifyFp option. 
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.by_trending(count=results, custom_verifyFp="*********", use_test_endpoints=True)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))
```
**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yoooby/Projects/Programming/lib/python3.8/site-packages/examples/get_trending.py", line 10, in <module>
    trending = api.by_trending(results)
  File "/home/yoooby/Projects/Programming/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 486, in by_trending
    ttwid = spawn.cookies["ttwid"]
  File "/home/yoooby/Projects/Programming/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/yoooby/Projects/Programming/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.1
 - TikTokApi Version Latest

i'm not using a server or vps i'm running it on my daily drive

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem

**Comment by krusalovorg** [comment]
I have the same problem
