### ISSUE TITLE
[BUG] - Can't parse tiktok site output

### ISSUE THREAD

**Issue by thousandsofthem** [davidteather/TikTok-Api#797]
```python
from TikTokApi import TikTokApi
api = TikTokApi.get_instance(custom_verifyFp="verify_xxx")
api.get_user("sarkisonchik")
```
The code produces output

```
ERROR:root:Tiktok response: 
<!DOCTYPE html><!DOCTYPE html><html lang="en"><head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><style data-emotion="tiktok "></style>
<title data-rh="true">♠️Sarkis&amp;Eka♠️ (@sarkisonchik) TikTok | Watc♠️Sdatarkis&amp;Eka♠️&#x27;s Newest TikTok Vids</title>
...
<script id="sigi-persisted-data">window['SIGI_STATE']={"AppContext":{"appContext":{"$baseUrl":"","$fullUrl":"","$isAndroid":false,"$isIMessage":false,"$isIOS":false,"$pageUrl":"e,"$host":"www.tiktok.com","$language":"en","$region":"NL","$appId":1233,"$appType":"m","$languageList":[
...
"SEO":{"metaParams":{"title":"♠️Sarkis&Eka♠️ (@sarkisonchik) TikTok | Watch ♠️Sarkis&Eka♠️'s Nt TikTokorth Videos","keywords":"♠️Sarkis&Eka♠️92,sa1427754",TikTok, ティックトック, tik tok, tick tock, tic tok, tic toc, tictok, тик ток, ticktock","description":"♠️Sarkis&Eka♠️ (@wssarkisonchik) on TikTok | 25.8M Likes. 867.2K Fans. 🔥СЕМЕЙisonchiku002F\u002Fm.tiktok.com","rootApi":"https:\u002F\u002Fwww.tiktok.com","secSDK"https:\u002F\u002Fwww.tiktok.com\u002F@sarkisonchik","robotsContent":"index, follow, max-image-previe
w:large","apаlicableDevice":"pc, mobile"},"jsonldList":[[wItemLiit",{}],["BreadcrumbList",{"itemListElement":[{"@type":"ListItem","position":1,"item":{"@type":"Thing","@id":"https:\u002F\u002Fwww.tiktok.com","name":"TikTok"}},{"@type":"ListItem","position":2,"item":{"@type":"Thing","@id":"https:\u002F\u002Fwww.tiktok.com\u002F@sarkisonchik",
...
</script></body></html>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1333, in get_user
    j_raw = self.__extract_tag_contents(r.text)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1553, in __extract_tag_contents
    nonce = html.split(nonce_start)[1].split(nonce_end)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1339, in get_user
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters
```

Which means lib can fetch user page successfully, but unable to parse it, masking real error "IndexError: list index out of range" with other non-existing error "TikTok blocks this request displaying a Captcha"

TikTokApi version V4.1.0
OS: installed in docker container as described in "Docker Installation" readme section

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
