### ISSUE TITLE
[BUG] - does not work "by_username()"

### ISSUE THREAD

**Issue by DoradoV** [davidteather/TikTok-Api#798]
```
from TikTokApi import TikTokApi

api = TikTokApi.get_instance(custom_verifyFp="*************")

usern = api.by_username("alexbar068")

print(usern)
```

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py", line 1333, in get_user
    j_raw = self.__extract_tag_contents(r.text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py", line 1553, in __extract_tag_contents
    nonce = html.split(nonce_start)[1].split(nonce_end)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Документация\Projects\tik-tok-printer\main.py", line 5, in <module>
    usern = api.by_username("alexbar068", custom_verifyFp="verify_kyk37ehm_0EVesCYN_sSKC_4imD_Afpe_B3SEAW6FAXcz")
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py", line 700, in by_username
    data = self.get_user_object(username, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py", line 1301, in get_user_object
    return self.get_user(username, **kwargs)["userInfo"]["user"]
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py", line 1339, in get_user
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

Process returned 1 (0x1)        execution time : 2.251 s
```

**Comment by walterjesus88** [comment]
https://github.com/davidteather/TikTok-Api/issues/787#issuecomment-1005124620

**Comment by sedanijay** [comment]
same issue from many days. @davidteather

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
