### ISSUE TITLE
Installation instruction Version 5.0.0 and solution for `metadata-generation-failed` 

### ISSUE THREAD

**Issue by Nouhelgod** [davidteather/TikTok-Api#812]
To install v5.0.0 (Work in progress) try:
`pip install git+https://github.com/davidteather/TikTok-Api.git@v5.0.0`

Next error occurred during the installation:
````
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "...\Temp\pip-req-build-1f1qfkm8\setup.py", line 6, in <module>
          long_description = fh.read()
        File "...\python39\lib\encodings\cp1251.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2947: character maps to <undefined>  
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

To fix that, I am just forked repository and replaced all text in **README.md** with only one link. 
If you encountered the same error, you can use `pip install git+https://github.com/Nouhelgod/TikTok-Api@v5.0.0` to avoid it.

**Comment by davidteather** [comment]
Think I fixed this with encoding='utf-8' in setup.py

**Comment by Nouhelgod** [comment]
Everything works fine, thank You!
