### ISSUE TITLE
[BUG] certificate error when running example code

### ISSUE THREAD

**Issue by Xodarap** [davidteather/TikTok-Api#83]
**Describe the bug**

I'm getting a certificate error when trying to run the Quickstart.

**The buggy code**

```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from TikTokApi import TikTokApi
>>> results=10
>>> api=TikTokApi()
>>> trending=api.trending(results)
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "D:\anaconda\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\anaconda\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "D:\anaconda\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "D:\anaconda\lib\site-packages\urllib3\connection.py", line 360, in connect
    ssl_context=context,
  File "D:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda\lib\site-packages\TikTokApi\tiktok.py", line 62, in trending
    b = browser(api_url)
  File "D:\anaconda\lib\site-packages\TikTokApi\browser.py", line 27, in __init__
    asyncio.get_event_loop().run_until_complete(self.start())
  File "D:\anaconda\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "D:\anaconda\lib\site-packages\TikTokApi\browser.py", line 30, in start
    self.browser = await pyppeteer.launch(self.options)
  File "D:\anaconda\lib\site-packages\pyppeteer\launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "D:\anaconda\lib\site-packages\pyppeteer\launcher.py", line 119, in __init__
    download_chromium()
  File "D:\anaconda\lib\site-packages\pyppeteer\chromium_downloader.py", line 146, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "D:\anaconda\lib\site-packages\pyppeteer\chromium_downloader.py", line 85, in download_zip
    data = http.request('GET', url, preload_content=False)
  File "D:\anaconda\lib\site-packages\urllib3\request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "D:\anaconda\lib\site-packages\urllib3\request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "D:\anaconda\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "D:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\anaconda\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromium-browser-snapshots/Win_x64/588429/chrome-win32.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.0

**Comment by Xodarap** [comment]
Run pyppeteer first with:
pyppeteer-install
