### ISSUE TITLE
[INSTALLATION] - requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Jerrywangmax** [davidteather/TikTok-Api#841]
Describe the error
I need to use VPN to login www.tiktok.com, but when i finished coding , displayed the below errors:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023FE34B5640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

I thought maybe was VPN problem, but i am not sure, have anyone can help me to solve this issue, thank you very much.

**The buggy code**

```
from TikTokApi import TikTokApi

api = TikTokApi(custom_verify_fp="******")
for video in api.trending.videos(count=50):
    print(video.as_dict)
```
**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "D:\software\Python\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\software\Python\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\software\Python\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\software\Python\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\software\Python\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\software\Python\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023FE34B5640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\software\Python\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\software\Python\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023FE34B5640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\Python\Python projects\Test1\testing32.py", line 9, in <module>
    for video in api.trending.videos(count=50):
  File "D:\software\Python\lib\site-packages\TikTokApi\api\trending.py", line 35, in videos
    spawn = requests.head(
  File "D:\software\Python\lib\site-packages\requests\api.py", line 104, in head
    return request('head', url, **kwargs)
  File "D:\software\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\software\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\software\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\software\Python\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023FE34B5640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Process finished with exit code 1
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows [10]
 - TikTokApi Version [5.0] 
 - Python Version  [3.95]

**Comment by peng741521840** [comment]
I have the same problem. Have you solved it?

**Comment by davidteather** [comment]
try with V6
