### ISSUE TITLE
KeyError: 'hasMore'

### ISSUE THREAD

**Issue by me-rgb** [davidteather/TikTok-Api#844]
Whenever I run this
tiktoks = api.trending()
It returns this error. Also, I am bad at coding so please make it simple for me :)

Traceback (most recent call last):
  File "C:\Users\AdminNoMicrosoft\Downloads\automated-yt-channel-main\main.py", line 13, in <module>
    import procedures.DownloadVideos as download_tiktok
  File "C:\Users\AdminNoMicrosoft\Downloads\automated-yt-channel-main\procedures\DownloadVideos.py", line 15, in <module>
    tiktoks = api.trending()
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 413, in by_trending
    if not res["hasMore"] and not first:
KeyError: 'hasMore'

I thought what would happen is it would get trending videos

 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 5.0.0] - if out of date upgrade before posting an issue

**Comment by EllisMuch** [comment]
I believe there is an issue with .trending() currently.

**Comment by me-rgb** [comment]
> I believe there is an issue with .trending() currently.

any fix?

**Comment by Impre-visible** [comment]
Same problem for me

**Comment by davidteather** [comment]
Should be fixed in V6, if you notice any issues with this again lmk. I should be using `.get("key")` instead of `["key"]` to avoid this
