### ISSUE TITLE
Installation issue: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by qlchen1** [davidteather/TikTok-Api#875]
Can anyone help? 

I run pip install tiktokapi, Then it is getting following error. 

 Using cached TikTokApi-5.1.1.tar.gz (64 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\xiaoto~1\\appdata\\local\\temp\\pip-install-ih5dkv\\tiktokapi\\setup.py'"'"'; __file__='"'"'c:\\users\\xiaoto~1\\appdata\\local\\temp\\pip-install-ih5dkv\\tiktokapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\xiaoto~1\appdata\local\temp\pip-pip-egg-info-oroizo'
         cwd: c:\users\xiaoto~1\appdata\local\temp\pip-install-ih5dkv\tiktokapi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xiaoto~1\appdata\local\temp\pip-install-ih5dkv\tiktokapi\setup.py", line 5, in <module>
        with open("README.md", "r", encoding="utf-8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by qlchen1** [comment]
I resolved this. Removed the old Python installation. and re-install with the latest one. that get resolved.
