### ISSUE TITLE
RuntimeError: This event loop is already running Playwright 

### ISSUE THREAD

**Issue by Pytoolbox** [davidteather/TikTok-Api#877]
```
Traceback (most recent call last):

  File "C:\Users\Admin\Desktop\Tiktok-User-Video-Post-Scraper\test.py", line 12, in <module>
    with TikTokApi() as api:

  File "C:\Users\Admin\anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 119, in __init__
    self._initialize(

  File "C:\Users\Admin\anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 163, in _initialize
    self._browser = asyncio.get_event_loop().run_until_complete(

  File "C:\Users\Admin\anaconda3\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()

  File "C:\Users\Admin\anaconda3\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running

Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\Admin\anaconda3\lib\site-packages\playwright\_impl\_connection.py:174> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "C:\Users\Admin\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 136, in connect
    raise exc
  File "C:\Users\Admin\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 124, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Admin\anaconda3\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Admin\anaconda3\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Admin\anaconda3\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

```



# -*- coding: utf-8 -*-
"""
Created on Sun Apr 24 03:10:21 2022

@author: Admin
"""

from TikTokApi import TikTokApi
veryfyfp=""
# api=TikTokApi.get_instance(custom_verifyFp=veryfyfp,use_test_endpoints=True)
# Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
with TikTokApi() as api:
#     for trending_video in api.trending.videos(count=50):
#         # Prints the author's username of the trending video.
#         print(trending_video.author.username)
        
    user = api.user(username='therock')
    user.as_dict # -> dict of the user_object
    for video in user.videos():
        video.as_dict # -> dict of TikTok's video object as found when requesting the videos endpoint        
        print(video)



```

I dont know what im doing wrong here. installed playwright and dependencies already

**Comment by Bumraider** [comment]
I want to be able to download user videos from calling the video dictionary

**Comment by davidteather** [comment]
V6 fully async
