### ISSUE TITLE
[BUG] -api is down

### ISSUE THREAD

**Issue by lazezo2** [davidteather/TikTok-Api#892]
**Describe the bug**

nothing is work except get info by video id!

**The buggy code**

using by sound or by user examples not working any more

`%%writefile v5_by_sound.py
from TikTokApi import TikTokApi
	
verify_fp = "verify_xxx"
api = TikTokApi()
	
sound = api.sound(id="7016547803243022337")
	
for video in sound.videos():
	print(video.id)`

that is the output

`Traceback (most recent call last):
  File "v5_by_sound.py", line 9, in <module>
    for video in sound.videos():
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/api/sound.py", line 143, in videos
    res = self.parent.get_data(path, send_tt_params=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/tiktok.py", line 227, in get_data
    full_url, calc_tt_params=send_tt_params, **kwargs
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/TikTokApi/browser_utilities/browser.py", line 183, in sign_url
    wait_until="load",
  File "/usr/local/lib/python3.7/dist-packages/playwright/async_api/_generated.py", line 7604, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "/usr/local/lib/python3.7/dist-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.7/dist-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.7/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.7/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Unacceptable TLS certificate
=========================== logs ===========================
navigating to "https://www.tiktok.com/@redbull", waiting until "load"
============================================================
`
same happen with api.user example

**Comment by davidteather** [comment]
User fixed, but sound is still broken is known issue
