### ISSUE TITLE
[BUG] Error when running getTiktoksByHashtag

### ISSUE THREAD

**Issue by cplasabas** [davidteather/TikTok-Api#92]
Getting this error when running getTiktoksByHashtag

```
Converting response to JSON failed response is below (probably empty)

Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokApi\tiktok.py", line 34, in getData
    return r.json()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getTiktoksByHashtag.py", line 7, in <module>
    tiktoks = api.byHashtag('zendeechallenge', count=count)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokApi\tiktok.py", line 190, in byHashtag
    res = self.getData(api_url, b.signature, b.userAgent)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokApi\tiktok.py", line 38, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response
```

**Comment by davidteather** [comment]
This is most likely being caused by a rate limiting on TikTok's server. Issue #88 had a similar problem, not the same but it was similar with the response a server would send.

**Comment by justinripple** [comment]
I had the same issue. I read issue #88. I modified the code as follows:
######################
import time

from TikTokApi import TikTokApi
api = TikTokApi()
count = 10
tiktoks = api.byUsername('therock', count=count)

for tiktok in tiktoks:
    print(tiktok)
    time.sleep(30)**
#######################
However, it doesn't solve the problem. Please help!

**Comment by VivianoRiccardo** [comment]
Same error, what i did:
`from TikTokAPI import TikTokAPI`
`api = TikTokAPI(language = "en",region = "IN")`
`retval = api.getTrending(count=1)`

i think this wrapper doesn't work anymore

**Comment by idilkylmz** [comment]
> I had the same issue. I read issue #88. I modified the code as follows:
> ######################
> import time
> 
> from TikTokApi import TikTokApi
> api = TikTokApi()
> count = 10
> tiktoks = api.byUsername('therock', count=count)
> 
> for tiktok in tiktoks:
> print(tiktok)
> time.sleep(30)**
> #######################
> However, it doesn't solve the problem. Please help!

Hi justin I am having the same problem did you have a chance to fix it?
