### ISSUE TITLE
[BUG] - Remote end closed connection without response

### ISSUE THREAD

**Issue by klauria22** [davidteather/TikTok-Api#945]
**Describe the bug**
When attempting to retrieve a user's videos, the program does nothing for about a minute, then gives an error saying 'Remote end closed connection without response'. It was working until a few days ago, and I haven't changed anything since then. Anyone seen this issue?

**The buggy code**
```
def download_videos(username):
    user = api.user(username=username)

    i = 0
    for video in user.videos(count=30):
        video_data = video.bytes()

        video_title = "saved_videos\clip" + str(i) + ".mp4"
        with open(video_title, "wb") as out_file:
            out_file.write(video_data)
            print(video_title + ' downloaded!')
        i += 1
```
**Expected behavior**
It should retrieve the videos from the given user's account, then save it as a .mp4 file. This was working fine until recently.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\kevin\tiktokbot\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/kevin/PycharmProjects/tiktokbot/main.py", line 294, in <module>
    main()
  File "C:/Users/kevin/PycharmProjects/tiktokbot/main.py", line 178, in main
    amount_downloaded = download_videos(username)
  File "C:/Users/kevin/PycharmProjects/tiktokbot/main.py", line 66, in download_videos
    for video in user.videos(count=30):
  File "C:\Users\kevin\tiktokbot\lib\site-packages\TikTokApi\api\user.py", line 153, in videos
    self.__find_attributes()
  File "C:\Users\kevin\tiktokbot\lib\site-packages\TikTokApi\api\user.py", line 282, in __find_attributes
    for u in self.parent.search.users(self.username):
  File "C:\Users\kevin\tiktokbot\lib\site-packages\TikTokApi\api\search.py", line 106, in search_type
    path, subdomain=subdomain, ttwid=ttwid, **kwargs
  File "C:\Users\kevin\tiktokbot\lib\site-packages\TikTokApi\tiktok.py", line 301, in get_data
    **self._requests_extra_kwargs,
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\kevin\tiktokbot\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version: 5.2.2

**Additional context**

I loaded cookies into the api, no change from that either.

**Comment by davidteather** [comment]
Should be fixed in V6 I think?
