### ISSUE TITLE
[BUG] - Telegram Bot Error usin TikTokApi 5.2.2

### ISSUE THREAD

**Issue by YuraBeseda** [davidteather/TikTok-Api#977]
**Describe the bug**

I tried to make a Telegram bot for myself that would convert video links from tiktok into video itself so I wouldn't have to quit it every time (I know they already exist, but I wanted to try to make something like that myself). The idea was that the bot would receive the link and using TikTokApi I would create a video and send it through the bot to the user, but when trying to do such a thing, there was such an error, moreover, the same error occurred when I tried to create code for conversion in a separate API (Flask and Django), hoping that at least from it I will be able to access the video data, but even so it was not able to do, as far as I understood the error is associated with asyncio, but, unfortunately, about asynchrony and the library itself I do not know enough to fix the problem myself, please help!

**The buggy code**

```py
from telebot import TeleBot
from TikTokApi import TikTokApi

bot = TeleBot("TOKEN")
api = TikTokApi(logging_level=logging.INFO)


@bot.message_handler()
def get_user_text(message):
    if message.text.startswith("https://vm.tiktok.com/"):
        req_video = api.video(url=message.text)
        print(req_video.bytes())


bot.polling()


```

**Expected behavior**

In this example it was supposed to send the video data that I would later work with to create the video itself and send through the bot, but already at this point there are problems

**Error Trace**

```
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\TelegramBot\main.py", line 16, in <module>
    bot.polling()
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\__init__.py", line 1047, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\__init__.py", line 1122, in __threaded_polling
    raise e
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\__init__.py", line 1078, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\util.py", line 154, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\util.py", line 98, in run
    task(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\telebot\__init__.py", line 6086, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\Users\Admin\PycharmProjects\TelegramBot\main.py", line 13, in get_user_text
    print(req_video.bytes())
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\TikTokApi\api\video.py", line 113, in bytes
    video_data = self.info(**kwargs)
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\TikTokApi\api\video.py", line 74, in info
    return self.info_full(**kwargs)["itemInfo"]["itemStruct"]
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\TikTokApi\api\video.py", line 95, in info_full
    return self.parent.get_data(path, **kwargs)
  File "C:\Users\Admin\PycharmProjects\TelegramBot\venv\lib\site-packages\TikTokApi\tiktok.py", line 266, in get_data
    ) = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'WorkerThread2'.

Process finished with exit code 1
```

**Desktop:**
 - OS: Windows 10
 - TikTokApi Version: 5.2.2

**Comment by davidteather** [comment]
V6 fully async so probably fixes
