### ISSUE TITLE
[BUG] - User.info_full() Consider Using Proxy

### ISSUE THREAD

**Issue by SyrupTheSrc** [davidteather/TikTok-Api#993]
**Describe the bug**

I can successfully get api.user('garyvee')

But when I try to pull api.user('garyvee').info_full()

IT FAILS

**CODE**

```py
from TikTokApi import TikTokApi
api = TikTokApi()
user_info = api.user('garyvee')
print(user.info_full())
```
**Error Trace**
```
# Error Trace Here
Traceback (most recent call last):
  File "/Users/nay/Desktop/Development/PLAYGROUNDS/TIKTOK/TikTok_II.py", line 42, in <module>
    print(user_info.as_dict)
  File "/Users/nay/opt/anaconda3/envs/tiktokanalytics/lib/python3.8/site-packages/TikTokApi/api/user.py", line 302, in __getattr__
    self.as_dict = self.info()
  File "/Users/nay/opt/anaconda3/envs/tiktokanalytics/lib/python3.8/site-packages/TikTokApi/api/user.py", line 69, in info
    return self.info_full(**kwargs)["user"]
  File "/Users/nay/opt/anaconda3/envs/tiktokanalytics/lib/python3.8/site-packages/TikTokApi/api/user.py", line 103, in info_full
    data = extract_tag_contents(r.text)
  File "/Users/nay/opt/anaconda3/envs/tiktokanalytics/lib/python3.8/site-packages/TikTokApi/helpers.py", line 31, in extract_tag_contents
    raise CaptchaException(0, None,
TikTokApi.exceptions.CaptchaException: 0 -> TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verify_fp as method parameters
```

**Desktop:**
 - OS: macOS Big Sur
 - TikTokApi Version =5.0.0

**Additional context**
- If this api is working for anyone, how are you getting it to work?

**Comment by rizkya2911** [comment]
hello @SyrupTheSrc, you can still using this API? If yes, I just wanna ask how do you solve `KeyError: "name='ttwid', domain=None, path=None"` bug thanks

**Comment by 4meepo** [comment]
Same issue here.

**Comment by davidteather** [comment]
Should be fixed in V6
